-- Cluster 10 + additive columns (2026-08-16 drift verdict).
-- Orphan counts verified 0 for every FK below. PARKED (orphans, human decision needed):
--   stream_messages_user_id_users_id_fk (12,390 rows; 57 distinct ids, 31 are knowledge_avatar ids)
--   live_streams_host_id_users_id_fk (145 rows; 31 distinct ids, all knowledge_avatar ids)
BEGIN;
ALTER TABLE "ai_trading_setups" ADD COLUMN "actual_hold_time" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "actual_return" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "alternative_setups" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "backtest_results" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "confluence_factors" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "correlation_analysis" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "drawdown_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_executed" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_timing" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_type" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_zone" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "exit_executed" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_return" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_time_to_target" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_value" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "feature_importance" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "fibonacci_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "historical_performance" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "holding_period" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "is_bookmarked" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "is_triggered" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "kelly_percentage" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "last_validated" timestamp DEFAULT now();
ALTER TABLE "ai_trading_setups" ADD COLUMN "liquidity_assessment" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "market_conditions" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "max_drawdown" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "max_risk" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "model_confidence" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "model_version" text DEFAULT 'v1.0';
ALTER TABLE "ai_trading_setups" ADD COLUMN "news_analysis" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "optimal_execution" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "pattern_quality" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "position_size" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "probability_method" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "resistance_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "seasonality_bias" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "sector_strength" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "setup_strength" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "sharing_level" text DEFAULT 'private';
ALTER TABLE "ai_trading_setups" ADD COLUMN "similar_setups" text[];
ALTER TABLE "ai_trading_setups" ADD COLUMN "slippage_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "stop_loss" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "stop_type" text DEFAULT 'fixed';
ALTER TABLE "ai_trading_setups" ADD COLUMN "strategy" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "success_probability" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "supporting_indicators" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "support_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "tags" text[];
ALTER TABLE "ai_trading_setups" ADD COLUMN "target_zone" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "trading_hours" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "trailing_stop_distance" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "trend_alignment" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "updated_at" timestamp DEFAULT now();
ALTER TABLE "ai_trading_setups" ADD COLUMN "user_notes" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "user_rating" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "volatility_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "volume_confirmation" real;
ALTER TABLE "stream_predictions" ADD COLUMN "market_created" boolean DEFAULT false;
ALTER TABLE "stream_predictions" ADD COLUMN "market_id" varchar;
ALTER TABLE "stream_tips" ADD COLUMN "highlight_color" text;
ALTER TABLE "ai_trading_setups" ADD CONSTRAINT "ai_trading_setups_alert_id_pattern_alerts_id_fk" FOREIGN KEY ("alert_id") REFERENCES "public"."pattern_alerts"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_generated_summary_id_summaries_id_fk" FOREIGN KEY ("generated_summary_id") REFERENCES "public"."summaries"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_host_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("host_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_linked_bounty_id_bounties_id_fk" FOREIGN KEY ("linked_bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_linked_market_id_prediction_markets_id_fk" FOREIGN KEY ("linked_market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_avatar1_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar1_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_avatar2_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar2_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_messages" ADD CONSTRAINT "stream_messages_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_messages" ADD CONSTRAINT "stream_messages_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_participants" ADD CONSTRAINT "stream_participants_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_participants" ADD CONSTRAINT "stream_participants_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_predictor_id_users_id_fk" FOREIGN KEY ("predictor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_recipient_id_users_id_fk" FOREIGN KEY ("recipient_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_tipper_id_users_id_fk" FOREIGN KEY ("tipper_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "users" ADD CONSTRAINT "users_twitter_id_unique" UNIQUE("twitter_id");
COMMIT;
