export interface AvatarTradingPersona {
  handle: string;
  name: string;
  category: 'VC' | 'DeFi' | 'L1/L2' | 'Trading' | 'Bitcoin' | 'AI/Tech' | 'Infrastructure';
  tradingStyle: 'aggressive' | 'moderate' | 'conservative';
  riskTolerance: 'high' | 'medium' | 'low';
  longBias: number;
  closeChance: number;
  positionMultiplier: number;
  tradeFrequency: number;
  preferredAssets: { symbol: string; name: string; type: 'crypto' | 'stock'; weight: number }[];
  longReasons: string[];
  shortReasons: string[];
  closeReasons: string[];
  description: string;
  emoji: string;
}

export const AVATAR_TRADING_PERSONAS: Record<string, AvatarTradingPersona> = {
  pmarca: {
    handle: 'pmarca',
    name: 'Marc Andreessen',
    category: 'VC',
    tradingStyle: 'aggressive',
    riskTolerance: 'high',
    longBias: 0.82,
    closeChance: 0.2,
    positionMultiplier: 1.8,
    tradeFrequency: 0.55,
    preferredAssets: [
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 8 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 9 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 7 },
      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock', weight: 8 },
      { symbol: 'META', name: 'Meta', type: 'stock', weight: 7 },
      { symbol: 'MSFT', name: 'Microsoft', type: 'stock', weight: 6 },
      { symbol: 'GOOGL', name: 'Alphabet', type: 'stock', weight: 6 },
    ],
    longReasons: [
      'Software is eating the world and {asset} is the next course — adding to position',
      'It\'s time to build. {asset} represents the infrastructure layer of the future internet',
      'The technology supercycle is just getting started, {asset} is a generational buy',
      'Every major tech wave was called a bubble at this stage — going long {asset} with conviction',
      'The smartest founders I know are building on {asset}, that\'s all the signal I need',
      '{asset} is entering its deployment phase after years of installation — classic Carlota Perez cycle',
      'Strong contrarian buy on {asset} — when the crowd is fearful, VCs should be greedy',
    ],
    shortReasons: [
      '{asset} valuation disconnected from fundamentals, trimming exposure',
      'Regulatory overhang on {asset} creating near-term headwinds, tactical short',
      '{asset} facing competitive disruption from newer protocols, reducing position',
    ],
    closeReasons: [
      'Portfolio rebalancing — taking profits on {asset} to deploy into earlier-stage opportunities',
      'Thesis on {asset} fully played out for this cycle, rotating capital',
      '{asset} position sizing exceeded fund allocation limits, trimming to target',
    ],
    description: 'The legendary VC who coined "software is eating the world." Runs a16z with massive tech and crypto conviction, aggressive position sizing on infrastructure plays.',
    emoji: '🦁',
  },

  cdixon: {
    handle: 'cdixon',
    name: 'Chris Dixon',
    category: 'VC',
    tradingStyle: 'moderate',
    riskTolerance: 'medium',
    longBias: 0.78,
    closeChance: 0.18,
    positionMultiplier: 1.4,
    tradeFrequency: 0.45,
    preferredAssets: [
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 10 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 8 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 6 },
      { symbol: 'polkadot', name: 'DOT', type: 'crypto', weight: 5 },
      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock', weight: 4 },
      { symbol: 'avalanche-2', name: 'AVAX', type: 'crypto', weight: 5 },
    ],
    longReasons: [
      'Read Write Own — {asset} is the next evolution of the internet ownership layer',
      'We\'re still in the early innings of the crypto computing era, accumulating {asset}',
      '{asset} represents the "come for the tool, stay for the network" thesis in action',
      'The best founders are choosing {asset} ecosystem — that\'s the strongest leading indicator',
      'Web3 infrastructure like {asset} will create more value than web2 ever did',
      'Why {asset}? Because computer platforms follow predictable adoption curves and we\'re at the inflection',
    ],
    shortReasons: [
      '{asset} network metrics declining vs competitors, reducing exposure',
      'Developer activity on {asset} flattening — conviction lowering, tactical short',
      '{asset} protocol economics unsustainable at current valuations, hedging',
    ],
    closeReasons: [
      'Rotating {asset} gains into earlier-stage web3 infrastructure opportunities',
      '{asset} thesis timeline extended beyond expected horizon, taking profits',
      'Fund lifecycle requires distributing {asset} gains back to LPs',
    ],
    description: 'The philosopher-VC of crypto. Leads a16z crypto with deep web3 conviction, authored "Read Write Own," and invests with a thesis-driven approach to internet ownership.',
    emoji: '📖',
  },

  gavofyork: {
    handle: 'gavofyork',
    name: 'Gavin Wood',
    category: 'L1/L2',
    tradingStyle: 'moderate',
    riskTolerance: 'medium',
    longBias: 0.72,
    closeChance: 0.22,
    positionMultiplier: 1.3,
    tradeFrequency: 0.5,
    preferredAssets: [
      { symbol: 'polkadot', name: 'DOT', type: 'crypto', weight: 10 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 8 },
      { symbol: 'avalanche-2', name: 'AVAX', type: 'crypto', weight: 5 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 4 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 6 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 4 },
    ],
    longReasons: [
      'The multi-chain future is inevitable — {asset} is positioned for cross-chain interoperability',
      'Substrate-based chains prove the heterogeneous sharding thesis, accumulating {asset}',
      '{asset} parachain ecosystem growing — shared security model is the correct architecture',
      'Web3 means trustless interaction across chains. {asset} delivers that vision',
      'JAM protocol evolution validates the {asset} ecosystem approach to scalable blockchains',
      'Governance innovation on {asset} is years ahead — on-chain upgradability is key',
    ],
    shortReasons: [
      '{asset} monolithic architecture will struggle at scale, reducing exposure',
      'Centralization concerns with {asset} validator set — short-term hedge',
      '{asset} failing to attract parachain developers, trimming position',
    ],
    closeReasons: [
      'Rebalancing toward Substrate ecosystem projects, closing {asset} position',
      '{asset} interoperability thesis needs reassessment after protocol changes',
      'Taking profits on {asset} to fund core protocol development',
    ],
    description: 'Ethereum co-founder who wrote Solidity, then created Polkadot and Substrate. Trades with deep conviction in multi-chain interoperability and heterogeneous sharding.',
    emoji: '🕸️',
  },

  IOHK_Charles: {
    handle: 'IOHK_Charles',
    name: 'Charles Hoskinson',
    category: 'L1/L2',
    tradingStyle: 'moderate',
    riskTolerance: 'medium',
    longBias: 0.75,
    closeChance: 0.2,
    positionMultiplier: 1.5,
    tradeFrequency: 0.45,
    preferredAssets: [
      { symbol: 'cardano', name: 'ADA', type: 'crypto', weight: 10 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 6 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 5 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 5 },
      { symbol: 'polkadot', name: 'DOT', type: 'crypto', weight: 4 },
    ],
    longReasons: [
      'Peer-reviewed research validates {asset} — science wins in the long run',
      '{asset} proof-of-stake implementation is the most rigorously verified in the industry',
      'Africa adoption proves {asset} real-world utility — 5 million users can\'t be wrong',
      'Hydra scaling solution brings {asset} throughput to 1M TPS — fundamentally undervalued',
      'The academic approach to {asset} development means fewer exploits, more trust, more adoption',
      'Governance on {asset} through Voltaire era makes it the most decentralized protocol',
    ],
    shortReasons: [
      '{asset} development velocity not matching hype cycle, protective short',
      'Smart contract ecosystem on {asset} losing market share to faster-moving chains',
      '{asset} TVL metrics concerning relative to market cap, hedging position',
    ],
    closeReasons: [
      'Research milestones on {asset} delayed, reassessing timeline and closing position',
      'Rotating {asset} profits into Cardano ecosystem projects and RealFi initiatives',
      '{asset} governance vote outcome changes thesis, taking profits',
    ],
    description: 'Cardano founder and Ethereum co-founder. Academic, research-driven trader who believes in peer-reviewed blockchain development and formal verification above all.',
    emoji: '🎓',
  },

  bgarlinghouse: {
    handle: 'bgarlinghouse',
    name: 'Brad Garlinghouse',
    category: 'Infrastructure',
    tradingStyle: 'moderate',
    riskTolerance: 'medium',
    longBias: 0.8,
    closeChance: 0.22,
    positionMultiplier: 1.4,
    tradeFrequency: 0.5,
    preferredAssets: [
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 7 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 6 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 5 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 6 },
      { symbol: 'MSFT', name: 'Microsoft', type: 'stock', weight: 4 },
    ],
    longReasons: [
      '{asset} is the bridge between TradFi and crypto — institutional adoption is accelerating',
      'Cross-border payments using {asset} save banks 60% on transaction costs, going long',
      'SEC clarity finally coming — {asset} regulatory risk repriced, accumulating',
      'Enterprise blockchain adoption of {asset} by top-100 banks validates the thesis',
      'ODL corridors expanding globally — {asset} utility driving fundamental value',
      'The Internet of Value needs {asset} as settlement infrastructure, strong buy',
    ],
    shortReasons: [
      '{asset} facing regulatory uncertainty in key jurisdictions, tactical hedge',
      'Competing payment rails gaining enterprise traction vs {asset}, reducing exposure',
      '{asset} token velocity problem eroding price support, short-term short',
    ],
    closeReasons: [
      'Regulatory outcome on {asset} requires position reassessment, closing',
      '{asset} enterprise partnership milestones achieved, taking profits to redeploy',
      'Portfolio overweight {asset} relative to mandate, trimming to target allocation',
    ],
    description: 'Ripple CEO who fought and won vs the SEC. Trades with enterprise-first conviction, focused on institutional crypto adoption and cross-border payment infrastructure.',
    emoji: '🏛️',
  },

  jespow: {
    handle: 'jespow',
    name: 'Jesse Powell',
    category: 'Bitcoin',
    tradingStyle: 'conservative',
    riskTolerance: 'low',
    longBias: 0.8,
    closeChance: 0.15,
    positionMultiplier: 1.0,
    tradeFrequency: 0.35,
    preferredAssets: [
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 10 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 7 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 4 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 3 },
      { symbol: 'dogecoin', name: 'DOGE', type: 'crypto', weight: 2 },
    ],
    longReasons: [
      'Been in {asset} since 2011 — the fundamentals have never been stronger',
      '{asset} exchange volumes hitting new highs, institutional order flow is real',
      'Custody infrastructure for {asset} is finally institutional-grade, adding position',
      'The {asset} market structure has matured — this isn\'t 2014 anymore, buy the dip',
      '{asset} spot ETF flows are the most bullish signal since the genesis block',
      'Running an exchange taught me: {asset} on-chain metrics don\'t lie, accumulating',
    ],
    shortReasons: [
      '{asset} exchange reserves spiking — distribution event likely, tactical short',
      'Leverage in {asset} derivatives market overextended, hedging with short',
      '{asset} funding rates extremely positive — crowded long, taking the other side',
    ],
    closeReasons: [
      '{asset} reached target allocation, disciplined profit taking',
      'Exchange-level data shows {asset} whale distribution, closing to reassess',
      '{asset} volatility exceeding risk parameters, closing to preserve capital',
    ],
    description: 'Kraken founder and OG Bitcoiner since 2011. Conservative, exchange-veteran trader who reads order books like a book and trusts on-chain data above all else.',
    emoji: '🐙',
  },

  haydenzadams: {
    handle: 'haydenzadams',
    name: 'Hayden Adams',
    category: 'DeFi',
    tradingStyle: 'aggressive',
    riskTolerance: 'high',
    longBias: 0.7,
    closeChance: 0.3,
    positionMultiplier: 1.6,
    tradeFrequency: 0.65,
    preferredAssets: [
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 10 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 5 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 7 },
      { symbol: 'avalanche-2', name: 'AVAX', type: 'crypto', weight: 5 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 4 },
    ],
    longReasons: [
      'DEX volume on {asset} chains hitting ATH — AMMs are eating CEX market share',
      '{asset} DeFi TVL growing — more liquidity means more efficient price discovery',
      'Concentrated liquidity on {asset} pools generating 3x more fees, going long ecosystem',
      'Every financial asset will eventually trade through AMMs — {asset} is the rails',
      'Uniswap v4 hooks on {asset} unlock infinite DeFi composability, bullish',
      '{asset} gas fees dropping makes DEX trading economically viable for everyone',
    ],
    shortReasons: [
      '{asset} DEX volumes declining relative to CEX, DeFi rotation short',
      'MEV extraction on {asset} eroding LP profitability, reducing exposure',
      '{asset} liquidity fragmenting across too many chains, tactical short',
    ],
    closeReasons: [
      '{asset} AMM fee revenue declining, closing position to reassess LP dynamics',
      'Rotating {asset} profits into new DeFi protocol launches',
      '{asset} reached impermanent loss threshold, closing to rebalance LP strategy',
    ],
    description: 'Uniswap creator who revolutionized decentralized trading. Aggressive DeFi-native trader focused on AMM efficiency, DEX volumes, and liquidity dynamics.',
    emoji: '🦄',
  },

  StaniKulechov: {
    handle: 'StaniKulechov',
    name: 'Stani Kulechov',
    category: 'DeFi',
    tradingStyle: 'moderate',
    riskTolerance: 'medium',
    longBias: 0.73,
    closeChance: 0.25,
    positionMultiplier: 1.3,
    tradeFrequency: 0.5,
    preferredAssets: [
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 10 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 7 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 5 },
      { symbol: 'avalanche-2', name: 'AVAX', type: 'crypto', weight: 5 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 5 },
      { symbol: 'polkadot', name: 'DOT', type: 'crypto', weight: 3 },
    ],
    longReasons: [
      'DeFi lending on {asset} generating real yield — this is sustainable finance, not hype',
      '{asset} protocol revenue up 200% — revenue-generating DeFi is the future',
      'Flash loans on {asset} prove composability is DeFi\'s killer feature, adding position',
      'GHO stablecoin integration with {asset} ecosystem creates a flywheel, bullish',
      'Lens Protocol social graph on {asset} will onboard the next 100M DeFi users',
      '{asset} institutional lending demand growing — TradFi can\'t ignore these yields',
    ],
    shortReasons: [
      '{asset} lending utilization rates dropping, protocol revenue at risk, hedging',
      'Bad debt accumulation on {asset} lending pools, reducing exposure',
      '{asset} DeFi yields compressing — capital rotation likely, tactical short',
    ],
    closeReasons: [
      '{asset} lending market dynamics shifting, closing to redeploy into social DeFi',
      'Protocol governance on {asset} changing risk parameters, reassessing position',
      'Taking {asset} profits to fund Lens Protocol ecosystem development',
    ],
    description: 'Aave founder and Lens Protocol creator. Methodical DeFi builder who trades based on lending market dynamics, protocol revenue, and social graph adoption metrics.',
    emoji: '👻',
  },

  CryptoHayes: {
    handle: 'CryptoHayes',
    name: 'Arthur Hayes',
    category: 'Trading',
    tradingStyle: 'aggressive',
    riskTolerance: 'high',
    longBias: 0.65,
    closeChance: 0.35,
    positionMultiplier: 2.2,
    tradeFrequency: 0.7,
    preferredAssets: [
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 10 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 9 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 7 },
      { symbol: 'dogecoin', name: 'DOGE', type: 'crypto', weight: 4 },
      { symbol: 'avalanche-2', name: 'AVAX', type: 'crypto', weight: 3 },
      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock', weight: 5 },
    ],
    longReasons: [
      'The USD debasement thesis is playing out exactly as predicted — {asset} to the moon',
      'Central bank money printing creating a floor for {asset}, leveraged long',
      'BOJ yield curve control unwind will send {asset} parabolic — this is the trade of the decade',
      'Maelstrom Fund adding {asset} — when governments print, hard assets win',
      '{asset} is the release valve for global fiat debasement, full send',
      'Treasury refunding announcement is bullish for {asset} — more liquidity incoming',
      'The yen carry trade unwind is the most bullish macro setup for {asset} I\'ve ever seen',
    ],
    shortReasons: [
      '{asset} overleveraged longs about to get rekt — shorting into the euphoria',
      'Fed reverse repo draining liquidity from {asset}, tactical short before the pain',
      '{asset} funding rates screaming overleveraged — fading the degens',
      'Dollar milkshake theory kicking in, {asset} denominated in USD going down short-term',
    ],
    closeReasons: [
      '{asset} hit my take-profit — rotating into the next macro setup',
      'Geopolitical event changed the {asset} macro calculus, closing to reassess',
      '{asset} volatility regime shifting, closing leveraged position before the chop',
      'Taking profits on {asset} before the next FOMC — never fight the Fed',
    ],
    description: 'BitMEX co-founder and Maelstrom Fund CIO. Bold contrarian macro trader who trades global central bank policy, leveraged derivatives, and fiat debasement narratives.',
    emoji: '🔥',
  },

  AndreCronjeTech: {
    handle: 'AndreCronjeTech',
    name: 'Andre Cronje',
    category: 'DeFi',
    tradingStyle: 'aggressive',
    riskTolerance: 'high',
    longBias: 0.68,
    closeChance: 0.35,
    positionMultiplier: 1.8,
    tradeFrequency: 0.65,
    preferredAssets: [
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 9 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 6 },
      { symbol: 'avalanche-2', name: 'AVAX', type: 'crypto', weight: 5 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 5 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 4 },
    ],
    longReasons: [
      'I tested {asset} in prod and it survived — that\'s the ultimate audit, going long',
      'Yield optimization on {asset} vaults generating 40% APY sustainably, accumulating',
      '{asset} DeFi composability creating money legos nobody imagined possible',
      'Built three protocols this week and {asset} ecosystem handled all of them, bullish',
      'The ve(3,3) tokenomics model on {asset} chains is aligning incentives perfectly',
      'Real yield on {asset} means actual revenue, not ponzi emissions — buy signal',
    ],
    shortReasons: [
      '{asset} yield farms printing unsustainable emissions, shorting the ponzinomics',
      'Fork of {asset} protocol diluting ecosystem value, reducing exposure',
      '{asset} smart contract risk too high after latest exploit, tactical short',
    ],
    closeReasons: [
      '{asset} yield strategies exhausted, closing to build the next protocol iteration',
      'Found a higher-yield opportunity than {asset}, rotating capital',
      '{asset} governance capture by whales, closing position on principle',
    ],
    description: 'The DeFi mad scientist. Yearn Finance and Solidly creator who builds, ships, and trades at hyperspeed. Yield farming pioneer who tests in production.',
    emoji: '🧪',
  },

  rleshner: {
    handle: 'rleshner',
    name: 'Robert Leshner',
    category: 'DeFi',
    tradingStyle: 'conservative',
    riskTolerance: 'low',
    longBias: 0.7,
    closeChance: 0.2,
    positionMultiplier: 0.9,
    tradeFrequency: 0.4,
    preferredAssets: [
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 10 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 8 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 6 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 4 },
      { symbol: 'MSFT', name: 'Microsoft', type: 'stock', weight: 5 },
      { symbol: 'GOOGL', name: 'Alphabet', type: 'stock', weight: 4 },
    ],
    longReasons: [
      '{asset} is the institutional-grade DeFi infrastructure TradFi has been waiting for',
      'Superstate bringing {asset} treasury products on-chain — the bridge is being built',
      '{asset} lending markets proving DeFi can be boring, reliable, and profitable',
      'Institutional allocators entering {asset} through regulated vehicles — structural bid',
      'Risk-adjusted returns on {asset} superior to TradFi equivalents, measured accumulation',
      '{asset} protocol revenue growing quarter over quarter — fundamentals matter',
    ],
    shortReasons: [
      '{asset} regulatory classification risk increasing, hedging institutional portfolio',
      'TradFi competition eating into {asset} DeFi yields, reducing overweight position',
      '{asset} smart contract insurance costs rising — risk repricing, tactical short',
    ],
    closeReasons: [
      '{asset} position reached target return, disciplined exit per investment mandate',
      'Institutional LP capital call requires {asset} liquidity, orderly exit',
      '{asset} risk-reward no longer meeting institutional allocation criteria, closing',
    ],
    description: 'Compound founder and Robot Ventures partner building Superstate. Conservative institutional DeFi trader who bridges TradFi and crypto with measured, data-driven positions.',
    emoji: '🏦',
  },

  justinsuntron: {
    handle: 'justinsuntron',
    name: 'Justin Sun',
    category: 'L1/L2',
    tradingStyle: 'aggressive',
    riskTolerance: 'high',
    longBias: 0.78,
    closeChance: 0.3,
    positionMultiplier: 2.0,
    tradeFrequency: 0.7,
    preferredAssets: [
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 8 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 8 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 5 },
      { symbol: 'dogecoin', name: 'DOGE', type: 'crypto', weight: 4 },
      { symbol: 'avalanche-2', name: 'AVAX', type: 'crypto', weight: 4 },
      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock', weight: 3 },
    ],
    longReasons: [
      'TRON processes $60B+ in stablecoins — {asset} ecosystem benefiting from the same trend',
      '{asset} is the next 100x — I\'m putting my money where my mouth is, full position',
      'Just had lunch with Warren Buffett and even he would buy {asset} at these levels',
      'TRX hit ATH and {asset} is following the same trajectory, aggressive accumulation',
      '{asset} stablecoin integration growing — utility drives value, going big',
      'The future of finance is decentralized and {asset} is leading the charge',
    ],
    shortReasons: [
      '{asset} competitors launching superior features, tactical short before rotation',
      '{asset} hype cycle peaking — I know a top when I see one, taking profits short',
      'Market overextended on {asset}, short-term correction trade',
    ],
    closeReasons: [
      'Rotating {asset} profits into the next big announcement',
      '{asset} promotion cycle complete, taking profits to fund next initiative',
      '{asset} position served its purpose, closing to focus on TRON ecosystem',
    ],
    description: 'TRON founder and aggressive crypto promoter. High-conviction, high-frequency trader who goes big on momentum plays and dominates the stablecoin narrative.',
    emoji: '🚀',
  },

  sama: {
    handle: 'sama',
    name: 'Sam Altman',
    category: 'AI/Tech',
    tradingStyle: 'moderate',
    riskTolerance: 'medium',
    longBias: 0.8,
    closeChance: 0.2,
    positionMultiplier: 1.5,
    tradeFrequency: 0.5,
    preferredAssets: [
      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock', weight: 10 },
      { symbol: 'MSFT', name: 'Microsoft', type: 'stock', weight: 9 },
      { symbol: 'GOOGL', name: 'Alphabet', type: 'stock', weight: 8 },
      { symbol: 'AMD', name: 'AMD', type: 'stock', weight: 7 },
      { symbol: 'META', name: 'Meta', type: 'stock', weight: 6 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 5 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 4 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 3 },
    ],
    longReasons: [
      'AGI is coming faster than anyone expects — {asset} is the infrastructure pick-and-shovel play',
      'AI compute demand growing 10x annually, {asset} positioned to capture that value',
      '{asset} at the intersection of AI and crypto — two megatrends converging, strong buy',
      'Worldcoin proving digital identity at scale — {asset} benefits from the same adoption curve',
      'The AI revolution needs {asset} — compute, energy, and infrastructure are the bottleneck',
      'GPT-5 will change everything and {asset} is the infrastructure layer, accumulating',
    ],
    shortReasons: [
      '{asset} AI narrative overheated relative to actual revenue, tactical mean reversion short',
      'Compute costs declining faster than {asset} pricing power, reducing exposure',
      '{asset} regulatory risk from AI governance frameworks increasing, hedging',
    ],
    closeReasons: [
      '{asset} AI thesis needs updating after latest model capability jump, closing to reassess',
      'Rotating {asset} profits into earlier-stage AI infrastructure investments',
      '{asset} position sizing exceeded portfolio targets, disciplined trim',
    ],
    description: 'OpenAI CEO and Worldcoin founder. Trades at the intersection of AI and crypto, heavy on compute infrastructure stocks and digital identity tokens.',
    emoji: '🤖',
  },

  aeyakovenko: {
    handle: 'aeyakovenko',
    name: 'Anatoly Yakovenko',
    category: 'L1/L2',
    tradingStyle: 'aggressive',
    riskTolerance: 'high',
    longBias: 0.76,
    closeChance: 0.28,
    positionMultiplier: 1.7,
    tradeFrequency: 0.6,
    preferredAssets: [
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 10 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 6 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 5 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 4 },
      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock', weight: 5 },
      { symbol: 'AMD', name: 'AMD', type: 'stock', weight: 4 },
    ],
    longReasons: [
      '{asset} TPS metrics proving that performance wins — users choose speed, going long',
      'Firedancer validator client on {asset} doubles throughput, this is just the beginning',
      '{asset} mobile-first with Saga proves crypto needs to meet users where they are',
      'State compression on {asset} makes NFTs cost $0.001 — that\'s how you get to a billion users',
      '65,000 TPS on {asset} is not a benchmark, it\'s production reality, accumulating',
      '{asset} DeFi volume rivaling Ethereum at 1/100th the cost — market hasn\'t priced this in',
    ],
    shortReasons: [
      '{asset} network congestion issues resurfacing, hedging until stability returns',
      'Competing L1s copying {asset} tech with better tokenomics, tactical short',
      '{asset} validator economics under pressure from MEV, reducing overweight position',
    ],
    closeReasons: [
      '{asset} Firedancer upgrade timeline delayed, closing to reassess entry point',
      'Taking {asset} profits to invest in Solana ecosystem projects directly',
      '{asset} hit resistance at key technical level, closing for now',
    ],
    description: 'Solana founder and high-performance blockchain engineer. Technical trader who believes raw speed and low costs win, trades aggressively on Solana ecosystem catalysts.',
    emoji: '⚡',
  },

  APompliano: {
    handle: 'APompliano',
    name: 'Anthony Pompliano',
    category: 'Bitcoin',
    tradingStyle: 'moderate',
    riskTolerance: 'medium',
    longBias: 0.92,
    closeChance: 0.1,
    positionMultiplier: 1.5,
    tradeFrequency: 0.4,
    preferredAssets: [
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 10 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 3 },
      { symbol: 'AAPL', name: 'Apple', type: 'stock', weight: 2 },
      { symbol: 'NVDA', name: 'NVIDIA', type: 'stock', weight: 2 },
    ],
    longReasons: [
      'Bitcoin is the hardest money ever created — adding to {asset} position on every dip',
      'Every institution will eventually hold {asset} — we\'re watching it happen in real time',
      '{asset} is going to $500K this cycle — the math is simple: fixed supply, growing demand',
      'The Bitcoin treasury company thesis proves {asset} is the ultimate corporate reserve asset',
      'Long {asset} — when in doubt, zoom out. The 4-year chart has never lied',
      '{asset} is the only truly scarce digital asset — 21 million, forever, non-negotiable',
      'Nation-state adoption of {asset} is the most bullish macro signal in history',
    ],
    shortReasons: [
      'Tactically reducing {asset} exposure before halving sell-the-news event',
      '{asset} funding rates extremely elevated, small hedge to manage portfolio risk',
      'Short-term {asset} correction likely after 120% annual rally, small tactical short',
    ],
    closeReasons: [
      'Never truly closing {asset} — just trimming to add on the next dip',
      '{asset} reached short-term target, taking small profits to buy the next pullback',
      'Portfolio rebalancing requires trimming {asset} — reluctantly, and only slightly',
    ],
    description: 'The Bitcoin maximalist evangelist. ProCap founder who eats, sleeps, and breathes BTC. Almost exclusively long Bitcoin with diamond hands and macro conviction.',
    emoji: '🅱️',
  },

  katie_haun: {
    handle: 'katie_haun',
    name: 'Katie Haun',
    category: 'VC',
    tradingStyle: 'conservative',
    riskTolerance: 'low',
    longBias: 0.72,
    closeChance: 0.18,
    positionMultiplier: 1.0,
    tradeFrequency: 0.4,
    preferredAssets: [
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 9 },
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 8 },
      { symbol: 'solana', name: 'SOL', type: 'crypto', weight: 6 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 5 },
      { symbol: 'MSFT', name: 'Microsoft', type: 'stock', weight: 4 },
      { symbol: 'GOOGL', name: 'Alphabet', type: 'stock', weight: 4 },
    ],
    longReasons: [
      '{asset} regulatory clarity improving — former prosecutor perspective: compliance wins',
      'Institutional infrastructure for {asset} now meeting the bar I set at DOJ, accumulating',
      '{asset} security audit landscape maturing — fewer exploits means more institutional capital',
      'Coinbase board visibility confirms {asset} institutional demand is real and growing',
      'The $1.5B Haun Ventures fund deployed into {asset} ecosystem for a reason — conviction',
      '{asset} consumer crypto applications finally achieving product-market fit',
    ],
    shortReasons: [
      '{asset} facing potential enforcement action based on my regulatory pattern recognition',
      'Insider activity on {asset} triggering compliance red flags, reducing exposure',
      '{asset} market structure showing signs of manipulation, protective hedge',
    ],
    closeReasons: [
      '{asset} regulatory landscape shifting, closing to wait for legal clarity',
      'Fund mandate requires {asset} position exit at this valuation, disciplined close',
      '{asset} thesis fully priced in, rotating to earlier-stage portfolio companies',
    ],
    description: 'Haun Ventures founder, former federal prosecutor, and Coinbase board member. Conservative institutional crypto investor with a legal/regulatory edge and compliance-first approach.',
    emoji: '⚖️',
  },

  adam3us: {
    handle: 'adam3us',
    name: 'Adam Back',
    category: 'Bitcoin',
    tradingStyle: 'conservative',
    riskTolerance: 'low',
    longBias: 0.88,
    closeChance: 0.1,
    positionMultiplier: 1.2,
    tradeFrequency: 0.3,
    preferredAssets: [
      { symbol: 'bitcoin', name: 'BTC', type: 'crypto', weight: 10 },
      { symbol: 'ethereum', name: 'ETH', type: 'crypto', weight: 3 },
      { symbol: 'chainlink', name: 'LINK', type: 'crypto', weight: 2 },
    ],
    longReasons: [
      'Hashcash proof-of-work was the precursor — {asset} is the culmination of decades of cypherpunk work',
      '{asset} Liquid sidechain enabling confidential transactions and faster settlement, bullish',
      'Cited in the Bitcoin whitepaper for a reason — {asset} is inevitable sound money',
      '{asset} hash rate at all-time high — the network has never been more secure, accumulating',
      'Lightning Network capacity on {asset} growing exponentially — Layer 2 scaling works',
      '{asset} is the cypherpunk dream realized — privacy, sovereignty, sound money',
      'Every fiat currency in history has gone to zero. {asset} is the exit, accumulating forever',
    ],
    shortReasons: [
      '{asset} altcoin season pulling capital from Bitcoin, tactical hedge on overvalued alts',
      '{asset} leverage in system too high — even Bitcoiners need risk management',
      'Short-term {asset} miner capitulation creating selling pressure, temporary hedge',
    ],
    closeReasons: [
      '{asset} position trimmed to fund Blockstream product development',
      'Rare {asset} rebalance — only to buy back lower during miner-driven dips',
      '{asset} tax-loss harvesting for strategic purposes, will re-enter immediately',
    ],
    description: 'Blockstream CEO, Hashcash inventor, and Bitcoin OG cited in the whitepaper. Cypherpunk maximalist who holds Bitcoin with generational conviction and almost never sells.',
    emoji: '🔐',
  },
};

export function getAvatarPersona(handle: string): AvatarTradingPersona | undefined {
  return AVATAR_TRADING_PERSONAS[handle];
}

export function getAllAvatarHandles(): string[] {
  return Object.keys(AVATAR_TRADING_PERSONAS);
}
