import axios from 'axios';
import { stockMarketService } from './stockMarketService';
import { db } from '../db';
import { predictionMarkets } from '@shared/schema';
import { eq, desc } from 'drizzle-orm';
import { modelGateway } from '../lib/modelGateway';
import { getMarketPulse, type MarketPulse } from './comprehensiveMarketService';
import { findBannedAdvice } from '@shared/agentSignals';

/**
 * Numeric, provider-backed observations for the Alpha Desk section.  The
 * pulse is intentionally kept loose here: comprehensiveMarketService can add
 * provider fields without making the newsletter generator fabricate values.
 */
export interface AlphaDeskObservation {
  text: string;
  asOf?: string;
  delayed?: boolean;
}

export interface MarketHighlight {
  symbol: string;
  name: string;
  price: number;
  change24h: number;
  changePercent: number;
  isPositive: boolean;
}

export interface StockHighlight {
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePercent: number;
  isPositive: boolean;
  sector: string;
}

export interface HotMarket {
  question: string;
  yesPercent: number;
  volume: number;
  traders: number;
  /** Human label for the market's real deadline, e.g. "Oct 1" */
  resolves: string;
}

export interface UpcomingStream {
  title: string;
  time: string;
  emoji: string;
}

export interface NewsletterContent {
  subject: string;
  marketHighlights: MarketHighlight[];
  topGainers: MarketHighlight[];
  topLosers: MarketHighlight[];
  stockGainers: StockHighlight[];
  stockLosers: StockHighlight[];
  /** Single editorial paragraph generated by the model gateway (with factual fallback). */
  agentsBrief: string;
  /** 3–5 individually validated, numeric market observations. */
  alphaDesk?: AlphaDeskObservation[];
  cryptoAsOf?: string;
  cryptoDelayed?: boolean;
  totalMarketCap: string;
  btcDominance: string;
  btcPrice: number;
  btcChange: number;
  ethPrice: number;
  ethChange: number;
  spyPrice: number;
  spyChange: number;
  fearGreedIndex: number | null;
  hotMarkets: HotMarket[];
  upcomingStreams: UpcomingStream[];
  newsStories: Array<{
    title: string;
    url: string;
    source: string;
    published: string;
  }>;
}

function formatUsd(value: number): string {
  if (value >= 1e12) return `$${(value / 1e12).toFixed(2)}T`;
  if (value >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
  if (value >= 1e6) return `$${(value / 1e6).toFixed(2)}M`;
  return `$${value.toLocaleString('en-US', { maximumFractionDigits: 2 })}`;
}

function numberValue(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value);
}

/** Factual fallback used when the reasoning gateway is unavailable. */
function factualAlphaDesk(pulse: MarketPulse): AlphaDeskObservation[] {
  const rows: AlphaDeskObservation[] = [];
  const add = (text: string, section: any) => {
    if (!findBannedAdvice(text)) rows.push({ text, asOf: section.asOf, delayed: section.delayed });
  };
  const volumeCount = pulse.unusualVolumeCount?.data;
  if (numberValue(volumeCount)) add(`${volumeCount} assets are flagged for unusual volume.`, pulse.unusualVolumeCount);
  const horizon = Date.now() + 7 * 24 * 60 * 60 * 1000;
  for (const earning of pulse.earnings?.data || []) {
    const date = new Date(earning.date);
    if (earning.symbol && !Number.isNaN(date.getTime()) && date.getTime() <= horizon && date.getTime() >= Date.now()) {
      add(`${earning.symbol.toUpperCase()} has earnings scheduled on ${earning.date}.`, pulse.earnings);
    }
  }
  const marketCap = pulse.totalMarketCap?.data?.value;
  if (numberValue(marketCap)) add(`Total market capitalization is ${formatUsd(marketCap)}.`, pulse.totalMarketCap);
  const dominance = pulse.btcDominance?.data?.value;
  if (numberValue(dominance)) add(`Bitcoin dominance is ${dominance.toFixed(2)}%.`, pulse.btcDominance);
  const fear = pulse.fearGreed?.data;
  const fearValue = typeof fear === 'number' ? fear : fear?.value;
  if (numberValue(fearValue)) add(`The crypto Fear & Greed reading is ${fearValue}/100.`, pulse.fearGreed);
  for (const mover of (pulse.movers?.data || []).slice(0, 2)) {
    if (mover.symbol && numberValue(mover.change24h)) {
      add(`${mover.symbol.toUpperCase()} moved ${mover.change24h >= 0 ? '+' : ''}${mover.change24h.toFixed(2)}% over 24 hours.`, pulse.movers);
    }
  }
  return rows.slice(0, 5);
}

/**
 * Ask the reasoning tier for concise observations, then validate each bullet
 * independently. Invalid bullets are dropped rather than rewritten.
 */
export async function generateAlphaDesk(pulse: MarketPulse | null | undefined): Promise<AlphaDeskObservation[]> {
  if (!pulse) return [];
  const fallback = factualAlphaDesk(pulse);
  if (fallback.length === 0) return [];

  try {
    const result = await modelGateway.completeJson<{ bullets?: unknown[] }>({
      tier: 'reasoning',
      priority: 'background',
      tag: 'newsletter-alpha-desk',
      system: 'Select and order 3-5 observations from the supplied canonical candidates. Do not rewrite them or add facts. Return JSON: {"bullets":[{"id":0,"text":"<exact candidate text>"}]}.',
      user: JSON.stringify({
        asOf: pulse.asOf,
        delayed: pulse.delayed,
        candidates: fallback.map((candidate, id) => ({ id, ...candidate })),
        data: pulse
      }),
      maxTokens: 500,
      jsonSchema: {
        name: 'newsletter_alpha_desk',
        schema: { type: 'object', properties: { bullets: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, text: { type: 'string' } }, required: ['id', 'text'] } } }, required: ['bullets'] }
      }
    });
    const bullets = Array.isArray(result?.bullets) ? result.bullets : [];
    const accepted: AlphaDeskObservation[] = bullets
      .map((bullet: unknown): AlphaDeskObservation | null => {
        const id = typeof bullet === 'object' && bullet !== null && 'id' in bullet
          ? Number((bullet as { id?: unknown }).id) : -1;
        const text = typeof bullet === 'object' && bullet !== null && 'text' in bullet
          ? (bullet as { text?: unknown }).text : bullet;
        const candidate = Number.isInteger(id) && id >= 0 && id < fallback.length
          ? fallback[id] : fallback.find(item => item.text === text);
        // The server emits only an exact canonical candidate. A rewritten
        // sentence, even with matching numbers/symbols, is rejected.
        if (!candidate || typeof text !== 'string' || text !== candidate.text || findBannedAdvice(text)) return null;
        if (findBannedAdvice(candidate.text)) return null;
        return candidate;
      })
      .slice(0, 5)
      .filter((item): item is AlphaDeskObservation => item !== null);
    return accepted;
  } catch (error: any) {
    console.warn('Alpha Desk generation failed, using factual observations:', error?.message || error);
    return fallback;
  }
}

const MEME_COIN_PATTERNS = [
  'inu', 'shib', 'doge', 'pepe', 'elon', 'floki', 'baby',
  'moon', 'safe', 'rocket', 'meme', 'wojak', 'chad',
  'bonk', 'bome', 'wif', 'pepe2', 'dogelon'
];

function isMemeCoin(name: string, symbol: string): boolean {
  const lowerName = name.toLowerCase();
  const lowerSymbol = symbol.toLowerCase();
  return MEME_COIN_PATTERNS.some(pattern =>
    lowerName.includes(pattern) || lowerSymbol.includes(pattern)
  );
}

function calculateRelevanceScore(coin: any): number {
  const marketCapWeight = Math.log10(coin.marketCap || 1);
  const volumeWeight = Math.log10(coin.volume24h || 1);
  const priceChangeWeight = Math.abs(coin.percentChange24h);
  return marketCapWeight * volumeWeight * priceChangeWeight;
}

interface CryptoQuoteSimple {
  symbol: string;
  name: string;
  price: number;
  percentChange24h: number;
  marketCap: number;
  volume24h: number;
}

let lastGoodCrypto: { data: CryptoQuoteSimple[]; asOf: string } | null = null;
let cryptoFetchDelayed = false;
let coinGeckoWarned = false;
let fearGreedWarned = false;

/**
 * Fetch top cryptos directly from CoinGecko Pro API.
 * Falls back to public CoinGecko if Pro key is missing.
 * Returns an empty array only if both fail.
 */
async function fetchCryptoDataDirectFromCoinGecko(limit: number = 50): Promise<CryptoQuoteSimple[]> {
  const proKey = process.env.COINGECKO_PRO_API_KEY || '';
  const baseUrl = proKey
    ? 'https://pro-api.coingecko.com/api/v3'
    : 'https://api.coingecko.com/api/v3';
  const headers: Record<string, string> = proKey
    ? { 'x-cg-pro-api-key': proKey }
    : {};

  try {
    const response = await axios.get(`${baseUrl}/coins/markets`, {
      headers,
      params: {
        vs_currency: 'usd',
        order: 'market_cap_desc',
        per_page: limit,
        page: 1,
        sparkline: false,
        price_change_percentage: '24h'
      },
      timeout: 10000
    });

    if (!response.data || !Array.isArray(response.data)) {
      throw new Error('Invalid CoinGecko response');
    }

    const data = response.data
      .map((coin: any): CryptoQuoteSimple | null => {
        const values = [coin.current_price, coin.price_change_percentage_24h, coin.market_cap, coin.total_volume];
        if (!coin.symbol || !coin.name || values.some(value => typeof value !== 'number' || !Number.isFinite(value))) return null;
        return {
          symbol: coin.symbol.toUpperCase(), name: coin.name,
          price: coin.current_price, percentChange24h: coin.price_change_percentage_24h,
          marketCap: coin.market_cap, volume24h: coin.total_volume
        };
      })
      .filter((coin: CryptoQuoteSimple | null): coin is CryptoQuoteSimple => coin !== null);
    if (!data.length) throw new Error('CoinGecko returned no valid quotes');
    cryptoFetchDelayed = false;
    lastGoodCrypto = { data, asOf: new Date().toISOString() };
    return data;
  } catch (error: any) {
    cryptoFetchDelayed = true;
    if (!coinGeckoWarned) {
      coinGeckoWarned = true;
      console.warn('CoinGecko fetch failed; using last known-good data when available:', error.message);
    }
    return lastGoodCrypto?.data || [];
  }
}

/**
 * Simulated crypto data as last-resort fallback.
 * Uses realistic approximate values with small random variation
 * so prices never show $0.000 in the newsletter.
 */
function getSimulatedCryptoData(): CryptoQuoteSimple[] {
  const v = (base: number, range: number) => base + (Math.random() - 0.5) * range;
  const c = () => parseFloat(((Math.random() - 0.45) * 6).toFixed(2));

  return [
    { symbol: 'BTC',  name: 'Bitcoin',          price: v(84500, 2000),  percentChange24h: c(), marketCap: 1670000000000, volume24h: 35000000000 },
    { symbol: 'ETH',  name: 'Ethereum',          price: v(2000, 100),   percentChange24h: c(), marketCap: 240000000000,  volume24h: 12000000000 },
    { symbol: 'SOL',  name: 'Solana',            price: v(130, 10),     percentChange24h: c(), marketCap: 64000000000,   volume24h: 4000000000  },
    { symbol: 'BNB',  name: 'BNB',               price: v(580, 20),     percentChange24h: c(), marketCap: 85000000000,   volume24h: 2000000000  },
    { symbol: 'XRP',  name: 'XRP',               price: v(2.1, 0.15),   percentChange24h: c(), marketCap: 122000000000,  volume24h: 5000000000  },
    { symbol: 'ADA',  name: 'Cardano',           price: v(0.68, 0.05),  percentChange24h: c(), marketCap: 24000000000,   volume24h: 700000000   },
    { symbol: 'AVAX', name: 'Avalanche',         price: v(22, 2),       percentChange24h: c(), marketCap: 9000000000,    volume24h: 400000000   },
    { symbol: 'DOT',  name: 'Polkadot',          price: v(4.5, 0.3),    percentChange24h: c(), marketCap: 6800000000,    volume24h: 200000000   },
    { symbol: 'LINK', name: 'Chainlink',         price: v(13, 1),       percentChange24h: c(), marketCap: 8000000000,    volume24h: 500000000   },
    { symbol: 'ATOM', name: 'Cosmos',            price: v(4.2, 0.3),    percentChange24h: c(), marketCap: 1600000000,    volume24h: 100000000   },
    { symbol: 'UNI',  name: 'Uniswap',          price: v(6.5, 0.5),    percentChange24h: c(), marketCap: 3900000000,    volume24h: 200000000   },
    { symbol: 'NEAR', name: 'NEAR Protocol',     price: v(2.5, 0.2),    percentChange24h: c(), marketCap: 2900000000,    volume24h: 200000000   },
    { symbol: 'ARB',  name: 'Arbitrum',          price: v(0.38, 0.03),  percentChange24h: c(), marketCap: 1500000000,    volume24h: 150000000   },
    { symbol: 'OP',   name: 'Optimism',          price: v(0.75, 0.05),  percentChange24h: c(), marketCap: 1100000000,    volume24h: 120000000   },
    { symbol: 'INJ',  name: 'Injective',         price: v(12, 1),       percentChange24h: c(), marketCap: 1100000000,    volume24h: 150000000   },
  ];
}

/**
 * Fetch Fear & Greed Index from Alternative.me API
 */
async function fetchFearGreedIndex(): Promise<number | null> {
  try {
    const response = await fetch('https://api.alternative.me/fng/?limit=1');
    const data = await response.json();
    if (data && data.data && data.data[0]) {
      return parseInt(data.data[0].value, 10);
    }
    return null;
  } catch (error) {
    if (!fearGreedWarned) {
      fearGreedWarned = true;
      console.warn('Fear & Greed fetch failed; omitting unavailable value:', error);
    }
    return null;
  }
}

const MIN_MARKET_TRADERS = 25;

function formatResolvesLabel(deadline: Date): string {
  return deadline.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    timeZone: 'America/New_York'
  });
}

/**
 * Fetch hot prediction markets from database.
 * Only active markets whose deadline is in the future qualify; markets with
 * fewer than MIN_MARKET_TRADERS traders are excluded, unless we'd otherwise
 * end up with fewer than 2 markets — in that case the largest future-dated
 * market is included regardless of trader count.
 */
export async function fetchHotMarkets(now: Date = new Date()): Promise<HotMarket[]> {
  try {
    const markets = await db.select()
      .from(predictionMarkets)
      .where(eq(predictionMarkets.status, 'active'))
      .orderBy(desc(predictionMarkets.totalVolume))
      .limit(25);

    const futureMarkets = markets.filter(m => {
      const deadline = m.deadline ? new Date(m.deadline) : null;
      return deadline !== null && deadline.getTime() > now.getTime();
    });

    let qualified = futureMarkets.filter(m => (m.totalTrades || 0) >= MIN_MARKET_TRADERS);

    if (qualified.length < 2 && futureMarkets.length > 0) {
      // Include the largest future-dated market (by volume) regardless of
      // trader count rather than showing expired markets.
      const extras = futureMarkets
        .filter(m => !qualified.includes(m))
        .sort((a, b) => (b.totalVolume || 0) - (a.totalVolume || 0));
      qualified = [...qualified, ...extras.slice(0, 2 - qualified.length)];
    }

    return qualified.slice(0, 5).map(m => {
      const yesPrice = m.yesPrice || 5000;
      const yesPercent = Math.round((yesPrice / 10000) * 100);
      return {
        question: m.question,
        yesPercent,
        volume: m.totalVolume || 0,
        traders: m.totalTrades || 0,
        resolves: formatResolvesLabel(new Date(m.deadline))
      };
    });
  } catch (error) {
    console.error('Error fetching hot markets:', error);
    return [];
  }
}

/**
 * Fetch top stock movers from Finnhub API. Missing quotes are omitted.
 */
async function fetchStockMovers(): Promise<{ gainers: StockHighlight[]; losers: StockHighlight[]; spy: { price: number; change: number } }> {
  try {
    const movers = await stockMarketService.getTechAiMovers();

    const formatStock = (s: any): StockHighlight => ({
      symbol: s.symbol,
      name: s.name,
      price: s.price,
      change: s.change,
      changePercent: s.changePercent,
      isPositive: s.changePercent > 0,
      sector: s.sector
    });

    const gainers = movers.gainers.slice(0, 5).map(formatStock);
    const losers = movers.losers.slice(0, 5).map(formatStock);

    let spyData = { price: 0, change: 0 };
    try {
      const spyQuote = await stockMarketService.getStockQuote('SPY');
      if (spyQuote && spyQuote.c > 0) {
        spyData = { price: spyQuote.c, change: Number.isFinite(spyQuote.dp) ? spyQuote.dp : 0 };
      }
    } catch (e) {
      console.warn('Failed to fetch SPY quote; omitting unavailable quote');
    }

    return { gainers, losers, spy: spyData };
  } catch (error) {
    console.error('Error fetching stock movers:', error);
    return {
      gainers: [],
      losers: [],
      spy: { price: 0, change: 0 }
    };
  }
}

/** Get a date's calendar parts as they appear in the America/New_York timezone. */
function getEtParts(date: Date): { year: number; month: number; day: number; hour: number; minute: number; second: number } {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/New_York',
    year: 'numeric',
    month: 'numeric',
    day: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
    second: 'numeric',
    hour12: false
  }).formatToParts(date);
  const get = (type: string) => parseInt(parts.find(p => p.type === type)?.value || '0', 10);
  return {
    year: get('year'),
    month: get('month'),
    day: get('day'),
    hour: get('hour') % 24,
    minute: get('minute'),
    second: get('second')
  };
}

function formatEtDateLabel(date: Date): string {
  return date.toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    timeZone: 'America/New_York'
  });
}

/**
 * Get upcoming scheduled streams (daily 8:00 AM / 4:00 PM Eastern market updates).
 * Times are computed in America/New_York regardless of the server timezone,
 * and labeled "ET" (never a hardcoded "EST").
 */
export async function fetchUpcomingStreams(now: Date = new Date()): Promise<UpcomingStream[]> {
  try {
    const et = getEtParts(now);
    const DAY_MS = 24 * 60 * 60 * 1000;
    const etSecondsOfDay = et.hour * 3600 + et.minute * 60 + et.second;

    // A slot rolls to tomorrow only once its exact ET time has strictly passed;
    // at exactly 8:00:00 / 4:00:00 PM ET the just-starting stream stays today.
    const morningDate = etSecondsOfDay > 8 * 3600 ? new Date(now.getTime() + DAY_MS) : now;
    const afternoonDate = etSecondsOfDay > 16 * 3600 ? new Date(now.getTime() + DAY_MS) : now;

    return [
      {
        title: 'Morning Market Update',
        time: `${formatEtDateLabel(morningDate)} · 8:00 AM ET`,
        emoji: '🌅'
      },
      {
        title: 'Market Close Recap',
        time: `${formatEtDateLabel(afternoonDate)} · 4:00 PM ET`,
        emoji: '🌙'
      }
    ];
  } catch (error) {
    console.error('Error fetching upcoming streams:', error);
    return [];
  }
}

interface BriefInputs {
  btcPrice: number;
  btcChange: number;
  ethPrice: number;
  ethChange: number;
  spyPrice: number;
  spyChange: number;
  fearGreedIndex: number | null;
  stockGainers: StockHighlight[];
  stockLosers: StockHighlight[];
  topCryptoMover?: MarketHighlight;
}

function signedPct(n: number): string {
  return `${n >= 0 ? '+' : ''}${n.toFixed(2)}%`;
}

function fallbackBrief(i: BriefInputs): string {
  const dir = i.btcChange >= 0 ? 'rose' : 'fell';
  const stats = [
    i.btcPrice > 0 ? `Bitcoin ${dir} ${signedPct(i.btcChange)} to $${i.btcPrice.toLocaleString('en-US', { maximumFractionDigits: 0 })}` : null,
    i.ethPrice > 0 ? `Ether moved ${signedPct(i.ethChange)}` : null,
    i.spyPrice > 0 ? `SPY (S&P 500 ETF) changed ${signedPct(i.spyChange)}` : null,
    i.fearGreedIndex === null ? null : `crypto sentiment sits at ${i.fearGreedIndex}/100`
  ].filter(Boolean);
  return `${stats.join('; ')}.`;
}

/**
 * Generate "The Agents' Brief": a single 90–130 word editorial paragraph via
 * the model gateway. Observational and specific, never advisory. If the
 * gateway call fails for any reason, falls back to a plain factual sentence —
 * the newsletter is never sent without a brief and the send never crashes.
 */
export async function generateAgentsBrief(inputs: BriefInputs): Promise<string> {
  const {
    btcPrice, btcChange, ethPrice, ethChange, spyPrice, spyChange,
  fearGreedIndex, stockGainers, stockLosers, topCryptoMover
  } = inputs;

  const gainersDesc = stockGainers.slice(0, 3)
    .map(s => `${s.symbol} ${signedPct(s.changePercent)}`).join(', ') || 'none';
  const losersDesc = stockLosers.slice(0, 3)
    .map(s => `${s.symbol} ${signedPct(s.changePercent)}`).join(', ') || 'none';
  const cryptoMoverDesc = topCryptoMover
    ? `${topCryptoMover.symbol} ${signedPct(topCryptoMover.changePercent)}`
    : 'none';

  try {
    const result = await modelGateway.complete({
      tier: 'reasoning',
      priority: 'background',
      tag: 'newsletter-content-generator',
      system:
        'You are the editor of a financial newsletter written by autonomous AI trading agents. ' +
        'Write a single paragraph of 90-130 words summarizing today\'s market. Be observational ' +
        'and specific: reference the actual numbers you are given, and note tensions in the data ' +
        '(for example a fear reading while prices rise). NEVER give advice or recommendations — ' +
        'do not use words like "consider", "buy", "sell", or "opportunity", and do not suggest ' +
        'positioning of any kind. Plain prose only, no headings, no bullet points, no markdown.',
      user:
        `Today's data:\n` +
        `${btcPrice > 0 ? `- Bitcoin: $${btcPrice.toLocaleString('en-US', { maximumFractionDigits: 2 })} (${signedPct(btcChange)} 24h)\n` : ''}` +
        `${ethPrice > 0 ? `- Ethereum: $${ethPrice.toLocaleString('en-US', { maximumFractionDigits: 2 })} (${signedPct(ethChange)} 24h)\n` : ''}` +
        `${spyPrice > 0 ? `- SPY (S&P 500 ETF): ${signedPct(spyChange)} on the day\n` : ''}` +
       `${fearGreedIndex === null ? '' : `- Crypto Fear & Greed index: ${fearGreedIndex}/100\n`}` +
        `- Top stock gainers: ${gainersDesc}\n` +
        `- Top stock losers: ${losersDesc}\n` +
        `- Top crypto mover: ${cryptoMoverDesc}`,
      maxTokens: 400
    });
    const text = (result.content || '').trim();
    if (!text) return fallbackBrief(inputs);
    return text;
  } catch (error: any) {
    console.warn('Agents\' Brief generation failed, using factual fallback:', error?.message || error);
    return fallbackBrief(inputs);
  }
}

/**
 * Generate newsletter content from live crypto market data.
 * Data is provider-backed only. Unavailable providers are omitted rather than
 * represented with simulated market numbers.
 */
export async function generateNewsletterContent(): Promise<NewsletterContent> {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const dayOfWeek = now.toLocaleDateString('en-US', { weekday: 'long' });
  const subject = `📈 StreamAiX Market Alpha - ${dayOfWeek}, ${dateStr}`;

  try {
    const [rawCryptoData, fearGreedIndex, hotMarkets, upcomingStreams, stockData, marketPulse] = await Promise.all([
      fetchCryptoDataDirectFromCoinGecko(50),
      fetchFearGreedIndex(),
      fetchHotMarkets(),
      fetchUpcomingStreams(),
      fetchStockMovers(),
      getMarketPulse().catch((error: any) => {
        console.warn('Alpha Desk market pulse unavailable:', error?.message || error);
        return null;
      })
    ]);

    const cryptoData = rawCryptoData;

    const filteredCoins = cryptoData.filter(coin =>
      !isMemeCoin(coin.name, coin.symbol) &&
      coin.marketCap > 100000000 &&
      coin.volume24h > 1000000
    );

    const allCoins: (MarketHighlight & { relevanceScore: number })[] = filteredCoins.map(coin => ({
      symbol: coin.symbol.toUpperCase(),
      name: coin.name,
      price: coin.price,
      change24h: (coin.price * coin.percentChange24h) / 100,
      changePercent: coin.percentChange24h,
      isPositive: coin.percentChange24h > 0,
      relevanceScore: calculateRelevanceScore(coin)
    }));

    const gainers = allCoins
      .filter(c => c.isPositive)
      .sort((a, b) => b.relevanceScore - a.relevanceScore);

    const losers = allCoins
      .filter(c => !c.isPositive)
      .sort((a, b) => b.relevanceScore - a.relevanceScore);

    const topGainers = gainers.slice(0, 5);
    const topLosers = losers.slice(0, 5);
    const marketHighlights = allCoins.slice(0, 3);

    const btcData = allCoins.find(c => c.symbol === 'BTC');
    const ethData = allCoins.find(c => c.symbol === 'ETH');

    const topCryptoMover = [...topGainers, ...topLosers]
      .sort((a, b) => Math.abs(b.changePercent) - Math.abs(a.changePercent))[0];

    const agentsBrief = await generateAgentsBrief({
      btcPrice: btcData?.price || 0,
      btcChange: btcData?.changePercent || 0,
      ethPrice: ethData?.price || 0,
      ethChange: ethData?.changePercent || 0,
      spyPrice: stockData.spy.price,
      spyChange: stockData.spy.change,
      fearGreedIndex,
      stockGainers: stockData.gainers,
      stockLosers: stockData.losers,
      topCryptoMover
    });
    const alphaDesk = await generateAlphaDesk(marketPulse as MarketPulse | null);

    let newsStories: Array<{ title: string; url: string; source: string; published: string }> = [];
    try {
      const { marketDataService } = await import('./marketDataService');
      const newsArticles = await marketDataService.getFinancialNews(5);
      newsStories = newsArticles.map(article => ({
        title: article.title,
        url: article.url,
        source: article.source || 'CoinDesk',
        published: article.published
      }));
    } catch (error) {
      console.error('Error fetching news stories:', error);
    }

    return {
      subject,
      marketHighlights,
      topGainers,
      topLosers,
      stockGainers: stockData.gainers,
      stockLosers: stockData.losers,
      agentsBrief,
      alphaDesk,
      cryptoAsOf: lastGoodCrypto?.asOf,
      cryptoDelayed: cryptoFetchDelayed,
      totalMarketCap: numberValue(marketPulse?.totalMarketCap?.data?.value) ? formatUsd(marketPulse.totalMarketCap.data.value) : 'N/A',
      btcDominance: numberValue(marketPulse?.btcDominance?.data?.value) ? `${marketPulse.btcDominance.data.value.toFixed(2)}%` : 'N/A',
      btcPrice: btcData?.price || 0,
      btcChange: btcData?.changePercent || 0,
      ethPrice: ethData?.price || 0,
      ethChange: ethData?.changePercent || 0,
      spyPrice: stockData.spy.price,
      spyChange: stockData.spy.change,
      fearGreedIndex,
      hotMarkets,
      upcomingStreams,
      newsStories
    };
  } catch (error) {
    console.error('Error generating newsletter content; omitting unavailable provider data:', error);

    const fearGreed = await fetchFearGreedIndex().catch(() => null);
    const upcomingStreams = await fetchUpcomingStreams().catch(() => []);
    const hotMarkets = await fetchHotMarkets().catch(() => []);
    return {
      subject,
      marketHighlights: [],
      topGainers: [],
      topLosers: [],
      stockGainers: [],
      stockLosers: [],
      agentsBrief: '',
      alphaDesk: [],
      totalMarketCap: 'N/A',
      btcDominance: 'N/A',
      btcPrice: 0,
      btcChange: 0,
      ethPrice: 0,
      ethChange: 0,
      spyPrice: 0,
      spyChange: 0,
      fearGreedIndex: fearGreed,
      hotMarkets,
      upcomingStreams,
      newsStories: []
    };
  }
}

/**
 * Generate feature highlights for newsletter
 */
export function getFeatureHighlights(): Array<{ title: string; description: string; emoji: string }> {
  return [
    {
      emoji: '🤖',
      title: 'AI Agent Trading',
      description: 'Watch 100 autonomous agents analyze and trade on prediction markets 24/7'
    },
    {
      emoji: '📊',
      title: 'Prediction Markets',
      description: 'Trade YES/NO positions on crypto events with instant liquidity'
    },
    {
      emoji: '🎙️',
      title: 'Daily AI Streams',
      description: 'Tune into 8am & 4pm ET market briefings hosted by AI Knowledge Avatars'
    },
    {
      emoji: '💰',
      title: 'DeFi Bounties',
      description: 'Earn STREAM tokens by creating summaries of crypto content'
    },
    {
      emoji: '🎯',
      title: 'Smart Insights',
      description: 'AI-powered market intelligence with confidence scoring'
    },
    {
      emoji: '🚀',
      title: 'Base Network',
      description: 'Built on Ethereum L2 for fast, low-cost transactions'
    }
  ];
}
