-- Schema drift proposed by drizzle-kit push (captured 2026-08-15) and NOT applied.
-- The 20 missing tables were created separately with safe CREATE TABLE + FK statements.
-- Everything below is column-level drift on EXISTING tables. It includes DESTRUCTIVE
-- statements (DROP COLUMN with data, lossy type changes, constraint drops).
-- DO NOT APPLY without human review. See the data-loss list drizzle printed:
--   e.g. bounties: drop view_count/like_count/share_count (12,800 rows),
--   knowledge_avatars: drop sharpe_ratio/alpha_generated/... (52 rows),
--   stream_recordings: drop format/quality/title/view_count/processed_at (46 rows),
--   users: type changes on twitter_* columns (132 rows), and more.
ALTER TABLE "achievement_definitions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "points_config" DROP CONSTRAINT "points_config_key_key";
ALTER TABLE "waitlist" DROP CONSTRAINT "waitlist_email_key";
ALTER TABLE "waitlist" DROP CONSTRAINT "waitlist_unsubscribe_token_key";
ALTER TABLE "ai_agents" DROP CONSTRAINT "ai_agents_name_key";
ALTER TABLE "prediction_markets" DROP CONSTRAINT "prediction_markets_contract_market_id_key";
ALTER TABLE "knowledge_avatars" DROP CONSTRAINT "knowledge_avatars_handle_key";
ALTER TABLE "avatar_follows" DROP CONSTRAINT "avatar_follows_user_id_avatar_id_key";
ALTER TABLE "bounty_hunters" DROP CONSTRAINT "bounty_hunters_user_id_key";
ALTER TABLE "bounty_quality_scores" DROP CONSTRAINT "bounty_quality_scores_bounty_id_key";
ALTER TABLE "live_streams" DROP CONSTRAINT "live_streams_room_id_key";
ALTER TABLE "conversation_likes" DROP CONSTRAINT "conversation_likes_conversation_id_user_id_key";
ALTER TABLE "daily_login_streak" DROP CONSTRAINT "daily_login_streak_user_id_key";
ALTER TABLE "market_predictors" DROP CONSTRAINT "market_predictors_user_id_key";
ALTER TABLE "push_subscriptions" DROP CONSTRAINT "push_subscriptions_endpoint_key";
ALTER TABLE "referral_codes" DROP CONSTRAINT "referral_codes_code_key";
ALTER TABLE "stream_chat_commands" DROP CONSTRAINT "stream_chat_commands_command_key";
ALTER TABLE "achievements" DROP CONSTRAINT "achievements_key_key";
ALTER TABLE "user_achievements" DROP CONSTRAINT "user_achievements_user_achievement_unique";
ALTER TABLE "user_preferences" DROP CONSTRAINT "user_preferences_user_id_key";
ALTER TABLE "user_stream_settings" DROP CONSTRAINT "user_stream_settings_user_id_key";
ALTER TABLE "user_trading_profile" DROP CONSTRAINT "user_trading_profile_user_id_key";
ALTER TABLE "user_trading_stats" DROP CONSTRAINT "user_trading_stats_user_id_key";
ALTER TABLE "avatar_post_reactions" DROP CONSTRAINT "avatar_post_reactions_post_id_user_id_reaction_type_key";
ALTER TABLE "tradeable_tokens" DROP CONSTRAINT "tradeable_tokens_symbol_key";
ALTER TABLE "tradeable_tokens" DROP CONSTRAINT "tradeable_tokens_address_key";
ALTER TABLE "user_trades" DROP CONSTRAINT "user_trades_tx_hash_key";
ALTER TABLE "ai_positions" DROP CONSTRAINT "ai_positions_agent_id_fkey";
ALTER TABLE "ai_positions" DROP CONSTRAINT "ai_positions_market_id_fkey";
ALTER TABLE "ai_positions" DROP CONSTRAINT "ai_positions_prediction_id_fkey";
ALTER TABLE "prediction_markets" DROP CONSTRAINT "prediction_markets_creator_id_fkey";
ALTER TABLE "prediction_markets" DROP CONSTRAINT "prediction_markets_source_content_id_fkey";
ALTER TABLE "ai_predictions" DROP CONSTRAINT "ai_predictions_agent_id_fkey";
ALTER TABLE "ai_predictions" DROP CONSTRAINT "ai_predictions_market_id_fkey";
ALTER TABLE "ai_trades" DROP CONSTRAINT "ai_trades_agent_id_fkey";
ALTER TABLE "ai_trades" DROP CONSTRAINT "ai_trades_market_id_fkey";
ALTER TABLE "ai_trades" DROP CONSTRAINT "ai_trades_position_id_fkey";
ALTER TABLE "ai_trading_alerts" DROP CONSTRAINT "ai_trading_alerts_user_id_fkey";
ALTER TABLE "avatar_content_interactions" DROP CONSTRAINT "avatar_content_interactions_avatar_id_fkey";
ALTER TABLE "avatar_content_interactions" DROP CONSTRAINT "avatar_content_interactions_user_id_fkey";
ALTER TABLE "avatar_conversations" DROP CONSTRAINT "avatar_conversations_avatar_id_fkey";
ALTER TABLE "avatar_conversations" DROP CONSTRAINT "avatar_conversations_user_id_fkey";
ALTER TABLE "avatar_follows" DROP CONSTRAINT "avatar_follows_avatar_id_fkey";
ALTER TABLE "avatar_follows" DROP CONSTRAINT "avatar_follows_user_id_fkey";
ALTER TABLE "avatar_insights" DROP CONSTRAINT "avatar_insights_avatar_id_fkey";
ALTER TABLE "avatar_positions" DROP CONSTRAINT "avatar_positions_avatar_id_fkey";
ALTER TABLE "avatar_positions" DROP CONSTRAINT "avatar_positions_market_id_fkey";
ALTER TABLE "avatar_trades" DROP CONSTRAINT "avatar_trades_avatar_id_fkey";
ALTER TABLE "avatar_trades" DROP CONSTRAINT "avatar_trades_market_id_fkey";
ALTER TABLE "bot_performance_snapshots" DROP CONSTRAINT "bot_performance_snapshots_agent_id_fkey";
ALTER TABLE "bot_performance_snapshots" DROP CONSTRAINT "bot_performance_snapshots_avatar_id_fkey";
ALTER TABLE "bot_sim_trades" DROP CONSTRAINT "bot_sim_trades_agent_id_fkey";
ALTER TABLE "bot_sim_trades" DROP CONSTRAINT "bot_sim_trades_avatar_id_fkey";
ALTER TABLE "bot_stakes" DROP CONSTRAINT "bot_stakes_agent_id_fkey";
ALTER TABLE "bot_stakes" DROP CONSTRAINT "bot_stakes_avatar_id_fkey";
ALTER TABLE "bot_stakes" DROP CONSTRAINT "bot_stakes_user_id_fkey";
ALTER TABLE "bounty_engagements" DROP CONSTRAINT "bounty_engagements_bounty_id_fkey";
ALTER TABLE "bounty_engagements" DROP CONSTRAINT "bounty_engagements_user_id_fkey";
ALTER TABLE "bounty_hunters" DROP CONSTRAINT "bounty_hunters_user_id_fkey";
ALTER TABLE "bounty_quality_scores" DROP CONSTRAINT "bounty_quality_scores_bounty_id_fkey";
ALTER TABLE "bounty_quality_scores" DROP CONSTRAINT "bounty_quality_scores_summary_id_fkey";
ALTER TABLE "bounty_templates" DROP CONSTRAINT "bounty_templates_created_by_fkey";
ALTER TABLE "category_follows" DROP CONSTRAINT "category_follows_user_id_fkey";
ALTER TABLE "chat_messages" DROP CONSTRAINT "chat_messages_user_id_fkey";
ALTER TABLE "co_stream_sessions" DROP CONSTRAINT "co_stream_sessions_primary_host_id_fkey";
ALTER TABLE "co_stream_sessions" DROP CONSTRAINT "co_stream_sessions_primary_stream_id_fkey";
ALTER TABLE "conversations" DROP CONSTRAINT "conversations_author_id_fkey";
ALTER TABLE "conversations" DROP CONSTRAINT "conversations_linked_bounty_id_fkey";
ALTER TABLE "conversations" DROP CONSTRAINT "conversations_linked_market_id_fkey";
ALTER TABLE "conversations" DROP CONSTRAINT "conversations_linked_summary_id_fkey";
ALTER TABLE "conversations" DROP CONSTRAINT "conversations_parent_id_fkey";
ALTER TABLE "conversation_comments" DROP CONSTRAINT "conversation_comments_conversation_id_fkey";
ALTER TABLE "conversation_comments" DROP CONSTRAINT "conversation_comments_parent_comment_id_fkey";
ALTER TABLE "conversation_comments" DROP CONSTRAINT "conversation_comments_user_id_fkey";
ALTER TABLE "conversation_likes" DROP CONSTRAINT "conversation_likes_conversation_id_fkey";
ALTER TABLE "conversation_likes" DROP CONSTRAINT "conversation_likes_user_id_fkey";
ALTER TABLE "conversation_shares" DROP CONSTRAINT "conversation_shares_conversation_id_fkey";
ALTER TABLE "conversation_shares" DROP CONSTRAINT "conversation_shares_user_id_fkey";
ALTER TABLE "daily_login_streak" DROP CONSTRAINT "daily_login_streak_user_id_fkey";
ALTER TABLE "stream_debates" DROP CONSTRAINT "stream_debates_participant1_avatar_id_fkey";
ALTER TABLE "stream_debates" DROP CONSTRAINT "stream_debates_participant1_id_fkey";
ALTER TABLE "stream_debates" DROP CONSTRAINT "stream_debates_participant2_avatar_id_fkey";
ALTER TABLE "stream_debates" DROP CONSTRAINT "stream_debates_participant2_id_fkey";
ALTER TABLE "stream_debates" DROP CONSTRAINT "stream_debates_stream_id_fkey";
ALTER TABLE "stream_debates" DROP CONSTRAINT "stream_debates_winner_avatar_id_fkey";
ALTER TABLE "stream_debates" DROP CONSTRAINT "stream_debates_winner_id_fkey";
ALTER TABLE "debate_votes" DROP CONSTRAINT "debate_votes_debate_id_fkey";
ALTER TABLE "debate_votes" DROP CONSTRAINT "debate_votes_voter_id_fkey";
ALTER TABLE "governance_proposals" DROP CONSTRAINT "governance_proposals_proposer_id_fkey";
ALTER TABLE "governance_votes" DROP CONSTRAINT "governance_votes_proposal_id_fkey";
ALTER TABLE "governance_votes" DROP CONSTRAINT "governance_votes_voter_id_fkey";
ALTER TABLE "prediction_leagues" DROP CONSTRAINT "prediction_leagues_creator_id_fkey";
ALTER TABLE "league_participants" DROP CONSTRAINT "league_participants_league_id_fkey";
ALTER TABLE "league_participants" DROP CONSTRAINT "league_participants_user_id_fkey";
ALTER TABLE "league_trades" DROP CONSTRAINT "league_trades_league_id_fkey";
ALTER TABLE "league_trades" DROP CONSTRAINT "league_trades_market_trade_id_fkey";
ALTER TABLE "league_trades" DROP CONSTRAINT "league_trades_participant_id_fkey";
ALTER TABLE "market_trades" DROP CONSTRAINT "market_trades_market_id_fkey";
ALTER TABLE "market_trades" DROP CONSTRAINT "market_trades_user_id_fkey";
ALTER TABLE "learning_lessons" DROP CONSTRAINT "learning_lessons_module_id_fkey";
ALTER TABLE "learning_quizzes" DROP CONSTRAINT "learning_quizzes_lesson_id_fkey";
ALTER TABLE "liquidity_providers" DROP CONSTRAINT "liquidity_providers_market_id_fkey";
ALTER TABLE "liquidity_providers" DROP CONSTRAINT "liquidity_providers_user_id_fkey";
ALTER TABLE "market_positions" DROP CONSTRAINT "market_positions_market_id_fkey";
ALTER TABLE "market_positions" DROP CONSTRAINT "market_positions_user_id_fkey";
ALTER TABLE "market_predictors" DROP CONSTRAINT "market_predictors_user_id_fkey";
ALTER TABLE "market_price_history" DROP CONSTRAINT "market_price_history_market_id_fkey";
ALTER TABLE "market_resolutions" DROP CONSTRAINT "market_resolutions_market_id_fkey";
ALTER TABLE "market_resolutions" DROP CONSTRAINT "market_resolutions_resolved_by_fkey";
ALTER TABLE "multi_stream_sessions" DROP CONSTRAINT "multi_stream_sessions_primary_stream_id_fkey";
ALTER TABLE "multi_stream_sessions" DROP CONSTRAINT "multi_stream_sessions_user_id_fkey";
ALTER TABLE "paper_trades" DROP CONSTRAINT "paper_trades_signal_id_fkey";
ALTER TABLE "paper_trades" DROP CONSTRAINT "paper_trades_user_id_fkey";
ALTER TABLE "points_transactions" DROP CONSTRAINT "points_transactions_user_id_fkey";
ALTER TABLE "portfolios" DROP CONSTRAINT "portfolios_user_id_fkey";
ALTER TABLE "portfolio_assets" DROP CONSTRAINT "portfolio_assets_portfolio_id_fkey";
ALTER TABLE "portfolio_assets" DROP CONSTRAINT "portfolio_assets_user_id_fkey";
ALTER TABLE "portfolio_goals" DROP CONSTRAINT "portfolio_goals_portfolio_id_fkey";
ALTER TABLE "portfolio_goals" DROP CONSTRAINT "portfolio_goals_user_id_fkey";
ALTER TABLE "portfolio_insights" DROP CONSTRAINT "portfolio_insights_portfolio_id_fkey";
ALTER TABLE "portfolio_insights" DROP CONSTRAINT "portfolio_insights_user_id_fkey";
ALTER TABLE "portfolio_snapshots" DROP CONSTRAINT "portfolio_snapshots_portfolio_id_fkey";
ALTER TABLE "portfolio_snapshots" DROP CONSTRAINT "portfolio_snapshots_user_id_fkey";
ALTER TABLE "portfolio_transactions" DROP CONSTRAINT "portfolio_transactions_asset_id_fkey";
ALTER TABLE "portfolio_transactions" DROP CONSTRAINT "portfolio_transactions_portfolio_id_fkey";
ALTER TABLE "portfolio_transactions" DROP CONSTRAINT "portfolio_transactions_user_id_fkey";
ALTER TABLE "price_alerts" DROP CONSTRAINT "price_alerts_portfolio_id_fkey";
ALTER TABLE "price_alerts" DROP CONSTRAINT "price_alerts_user_id_fkey";
ALTER TABLE "push_subscriptions" DROP CONSTRAINT "push_subscriptions_user_id_fkey";
ALTER TABLE "referral_codes" DROP CONSTRAINT "referral_codes_user_id_fkey";
ALTER TABLE "referral_signups" DROP CONSTRAINT "referral_signups_referral_code_id_fkey";
ALTER TABLE "referral_signups" DROP CONSTRAINT "referral_signups_referred_user_id_fkey";
ALTER TABLE "referral_signups" DROP CONSTRAINT "referral_signups_referrer_id_fkey";
ALTER TABLE "scheduled_streams" DROP CONSTRAINT "scheduled_streams_host_avatar_id_fkey";
ALTER TABLE "scheduled_streams" DROP CONSTRAINT "scheduled_streams_host_id_fkey";
ALTER TABLE "scheduled_streams" DROP CONSTRAINT "scheduled_streams_stream_id_fkey";
ALTER TABLE "stream_alerts" DROP CONSTRAINT "stream_alerts_avatar_id_fkey";
ALTER TABLE "stream_alerts" DROP CONSTRAINT "stream_alerts_streamer_id_fkey";
ALTER TABLE "stream_alerts" DROP CONSTRAINT "stream_alerts_user_id_fkey";
ALTER TABLE "stream_chat_command_logs" DROP CONSTRAINT "stream_chat_command_logs_command_id_fkey";
ALTER TABLE "stream_chat_command_logs" DROP CONSTRAINT "stream_chat_command_logs_stream_id_fkey";
ALTER TABLE "stream_chat_command_logs" DROP CONSTRAINT "stream_chat_command_logs_user_id_fkey";
ALTER TABLE "stream_clips" DROP CONSTRAINT "stream_clips_creator_id_fkey";
ALTER TABLE "stream_clips" DROP CONSTRAINT "stream_clips_stream_id_fkey";
ALTER TABLE "stream_participants" DROP CONSTRAINT "stream_participants_avatar_id_fkey";
ALTER TABLE "stream_conversation_messages" DROP CONSTRAINT "stream_conversation_messages_participant_id_fkey";
ALTER TABLE "stream_conversation_messages" DROP CONSTRAINT "stream_conversation_messages_speaker_avatar_id_fkey";
ALTER TABLE "stream_conversation_messages" DROP CONSTRAINT "stream_conversation_messages_speaker_user_id_fkey";
ALTER TABLE "stream_conversation_messages" DROP CONSTRAINT "stream_conversation_messages_stream_id_fkey";
ALTER TABLE "stream_invitations" DROP CONSTRAINT "stream_invitations_debate_id_fkey";
ALTER TABLE "stream_invitations" DROP CONSTRAINT "stream_invitations_invitee_avatar_id_fkey";
ALTER TABLE "stream_invitations" DROP CONSTRAINT "stream_invitations_invitee_id_fkey";
ALTER TABLE "stream_invitations" DROP CONSTRAINT "stream_invitations_inviter_id_fkey";
ALTER TABLE "stream_invitations" DROP CONSTRAINT "stream_invitations_stream_id_fkey";
ALTER TABLE "stream_polls" DROP CONSTRAINT "stream_polls_creator_id_fkey";
ALTER TABLE "stream_polls" DROP CONSTRAINT "stream_polls_stream_id_fkey";
ALTER TABLE "stream_poll_votes" DROP CONSTRAINT "stream_poll_votes_poll_id_fkey";
ALTER TABLE "stream_poll_votes" DROP CONSTRAINT "stream_poll_votes_voter_id_fkey";
ALTER TABLE "stream_questions" DROP CONSTRAINT "stream_questions_asker_id_fkey";
ALTER TABLE "stream_questions" DROP CONSTRAINT "stream_questions_stream_id_fkey";
ALTER TABLE "stream_raids" DROP CONSTRAINT "stream_raids_from_stream_id_fkey";
ALTER TABLE "stream_raids" DROP CONSTRAINT "stream_raids_raider_id_fkey";
ALTER TABLE "stream_raids" DROP CONSTRAINT "stream_raids_to_stream_id_fkey";
ALTER TABLE "stream_reactions" DROP CONSTRAINT "stream_reactions_stream_id_fkey";
ALTER TABLE "stream_reactions" DROP CONSTRAINT "stream_reactions_user_id_fkey";
ALTER TABLE "stream_recordings" DROP CONSTRAINT "stream_recordings_parent_recording_id_fkey";
ALTER TABLE "stream_recordings" DROP CONSTRAINT "stream_recordings_stream_id_fkey";
ALTER TABLE "stream_schedule_reminders" DROP CONSTRAINT "stream_schedule_reminders_stream_id_fkey";
ALTER TABLE "stream_schedule_reminders" DROP CONSTRAINT "stream_schedule_reminders_user_id_fkey";
ALTER TABLE "stream_viewer_leaderboard" DROP CONSTRAINT "stream_viewer_leaderboard_stream_id_fkey";
ALTER TABLE "stream_viewer_leaderboard" DROP CONSTRAINT "stream_viewer_leaderboard_user_id_fkey";
ALTER TABLE "streamer_subscription_tiers" DROP CONSTRAINT "streamer_subscription_tiers_streamer_id_fkey";
ALTER TABLE "streamer_subscriptions" DROP CONSTRAINT "streamer_subscriptions_gifted_by_fkey";
ALTER TABLE "streamer_subscriptions" DROP CONSTRAINT "streamer_subscriptions_streamer_id_fkey";
ALTER TABLE "streamer_subscriptions" DROP CONSTRAINT "streamer_subscriptions_subscriber_id_fkey";
ALTER TABLE "super_chats" DROP CONSTRAINT "super_chats_sender_id_fkey";
ALTER TABLE "super_chats" DROP CONSTRAINT "super_chats_stream_id_fkey";
ALTER TABLE "tip_contributions" DROP CONSTRAINT "tip_contributions_bounty_id_fkey";
ALTER TABLE "tip_contributions" DROP CONSTRAINT "tip_contributions_tipper_id_fkey";
ALTER TABLE "trading_watchlist" DROP CONSTRAINT "trading_watchlist_user_id_fkey";
ALTER TABLE "user_achievements" DROP CONSTRAINT "user_achievements_achievement_id_fkey";
ALTER TABLE "user_achievements" DROP CONSTRAINT "user_achievements_user_id_fkey";
ALTER TABLE "user_learning_progress" DROP CONSTRAINT "user_learning_progress_current_lesson_id_fkey";
ALTER TABLE "user_learning_progress" DROP CONSTRAINT "user_learning_progress_module_id_fkey";
ALTER TABLE "user_learning_progress" DROP CONSTRAINT "user_learning_progress_user_id_fkey";
ALTER TABLE "user_lesson_completions" DROP CONSTRAINT "user_lesson_completions_lesson_id_fkey";
ALTER TABLE "user_lesson_completions" DROP CONSTRAINT "user_lesson_completions_module_id_fkey";
ALTER TABLE "user_lesson_completions" DROP CONSTRAINT "user_lesson_completions_user_id_fkey";
ALTER TABLE "user_preferences" DROP CONSTRAINT "user_preferences_user_id_fkey";
ALTER TABLE "user_quiz_attempts" DROP CONSTRAINT "user_quiz_attempts_lesson_id_fkey";
ALTER TABLE "user_quiz_attempts" DROP CONSTRAINT "user_quiz_attempts_quiz_id_fkey";
ALTER TABLE "user_quiz_attempts" DROP CONSTRAINT "user_quiz_attempts_user_id_fkey";
ALTER TABLE "user_stream_achievements" DROP CONSTRAINT "user_stream_achievements_achievement_id_fkey";
ALTER TABLE "user_stream_achievements" DROP CONSTRAINT "user_stream_achievements_user_id_fkey";
ALTER TABLE "user_stream_settings" DROP CONSTRAINT "user_stream_settings_user_id_fkey";
ALTER TABLE "user_trading_profile" DROP CONSTRAINT "user_trading_profile_user_id_fkey";
ALTER TABLE "user_trading_stats" DROP CONSTRAINT "user_trading_stats_user_id_fkey";
ALTER TABLE "viewer_watch_rewards" DROP CONSTRAINT "viewer_watch_rewards_stream_id_fkey";
ALTER TABLE "viewer_watch_rewards" DROP CONSTRAINT "viewer_watch_rewards_user_id_fkey";
ALTER TABLE "watchlist_items" DROP CONSTRAINT "watchlist_items_user_id_fkey";
ALTER TABLE "avatar_posts" DROP CONSTRAINT "avatar_posts_author_user_id_fkey";
ALTER TABLE "avatar_posts" DROP CONSTRAINT "avatar_posts_avatar_id_fkey";
ALTER TABLE "avatar_posts" DROP CONSTRAINT "avatar_posts_market_id_fkey";
ALTER TABLE "avatar_posts" DROP CONSTRAINT "avatar_posts_trade_id_fkey";
ALTER TABLE "avatar_post_reactions" DROP CONSTRAINT "avatar_post_reactions_post_id_fkey";
ALTER TABLE "avatar_post_reactions" DROP CONSTRAINT "avatar_post_reactions_user_id_fkey";
ALTER TABLE "agent_memory" DROP CONSTRAINT "agent_memory_agent_id_fkey";
ALTER TABLE "agent_memory" DROP CONSTRAINT "agent_memory_market_id_fkey";
ALTER TABLE "market_resolutions_audit" DROP CONSTRAINT "market_resolutions_audit_market_id_fkey";
ALTER TABLE "agent_suspensions" DROP CONSTRAINT "agent_suspensions_agent_id_fkey";
ALTER TABLE "bridge_requests" DROP CONSTRAINT "bridge_requests_user_id_fkey";
ALTER TABLE "ai_trading_setups" ALTER COLUMN "entry_conditions" SET DATA TYPE text[];
ALTER TABLE "ai_trading_setups" ALTER COLUMN "status" SET DEFAULT 'active';
ALTER TABLE "scheduled_debates" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "scheduled_debates" ALTER COLUMN "category" SET DATA TYPE text;
ALTER TABLE "scheduled_debates" ALTER COLUMN "scheduled_start_time" SET DATA TYPE timestamp;
ALTER TABLE "scheduled_debates" ALTER COLUMN "actual_start_time" SET DATA TYPE timestamp;
ALTER TABLE "scheduled_debates" ALTER COLUMN "end_time" SET DATA TYPE timestamp;
ALTER TABLE "scheduled_debates" ALTER COLUMN "status" SET DATA TYPE text;
ALTER TABLE "scheduled_debates" ALTER COLUMN "status" SET NOT NULL;
ALTER TABLE "scheduled_debates" ALTER COLUMN "created_at" SET DATA TYPE timestamp;
ALTER TABLE "stream_messages" ALTER COLUMN "message_type" SET NOT NULL;
ALTER TABLE "stream_messages" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "stream_messages" ALTER COLUMN "deleted_by" SET DATA TYPE varchar;
ALTER TABLE "stream_predictions" ALTER COLUMN "timestamp" SET DATA TYPE integer;
ALTER TABLE "stream_predictions" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "stream_tips" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "users" ALTER COLUMN "twitter_id" SET DATA TYPE text;
ALTER TABLE "users" ALTER COLUMN "twitter_username" SET DATA TYPE text;
ALTER TABLE "users" ALTER COLUMN "twitter_display_name" SET DATA TYPE text;
ALTER TABLE "users" ALTER COLUMN "auth_provider" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "name" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "handle" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "expertise" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "twitter_handle" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "is_active" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "follower_count" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "following_count" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "verification_status" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "updated_at" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "trading_style" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "risk_tolerance" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "max_position_pct" SET DATA TYPE real;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "decision_bias" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "trading_frequency" SET DATA TYPE text;
ALTER TABLE "avatar_content_interactions" ALTER COLUMN "interaction_type" SET DATA TYPE text;
ALTER TABLE "avatar_content_interactions" ALTER COLUMN "content_id" SET NOT NULL;
ALTER TABLE "avatar_content_interactions" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "avatar_follows" ALTER COLUMN "notifications_enabled" DROP NOT NULL;
ALTER TABLE "avatar_follows" ALTER COLUMN "followed_at" DROP NOT NULL;
ALTER TABLE "avatar_insights" ALTER COLUMN "category" SET DATA TYPE text;
ALTER TABLE "avatar_insights" ALTER COLUMN "category" DROP NOT NULL;
ALTER TABLE "avatar_insights" ALTER COLUMN "title" SET DATA TYPE text;
ALTER TABLE "avatar_insights" ALTER COLUMN "confidence" SET DATA TYPE integer;
ALTER TABLE "avatar_insights" ALTER COLUMN "confidence" SET DEFAULT 50;
ALTER TABLE "avatar_insights" ALTER COLUMN "published_at" DROP NOT NULL;
ALTER TABLE "avatar_insights" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "avatar_insights" ALTER COLUMN "insight_type" DROP DEFAULT;
ALTER TABLE "bounties" ALTER COLUMN "creator_wallet" SET NOT NULL;
ALTER TABLE "bounties" ALTER COLUMN "bounty_type" SET NOT NULL;
ALTER TABLE "live_streams" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "live_streams" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "market_price_history" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "market_price_history" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "portfolio_assets" ALTER COLUMN "annual_growth_rate" SET DATA TYPE real;
ALTER TABLE "portfolio_assets" ALTER COLUMN "contribution_amount" SET DATA TYPE real;
ALTER TABLE "stream_participants" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "stream_participants" ALTER COLUMN "joined_at" SET DEFAULT now();
ALTER TABLE "stream_participants" ALTER COLUMN "participant_type" SET NOT NULL;
ALTER TABLE "stream_recordings" ALTER COLUMN "id" SET DATA TYPE varchar;
ALTER TABLE "stream_recordings" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "stream_recordings" ALTER COLUMN "stream_id" SET DATA TYPE varchar;
ALTER TABLE "stream_recordings" ALTER COLUMN "recording_url" DROP NOT NULL;
ALTER TABLE "stream_recordings" ALTER COLUMN "duration_seconds" DROP DEFAULT;
ALTER TABLE "stream_recordings" ALTER COLUMN "duration_seconds" DROP NOT NULL;
ALTER TABLE "stream_recordings" ALTER COLUMN "file_size_bytes" SET DATA TYPE integer;
ALTER TABLE "stream_recordings" ALTER COLUMN "status" SET DATA TYPE text;
ALTER TABLE "stream_recordings" ALTER COLUMN "status" SET NOT NULL;
ALTER TABLE "stream_recordings" ALTER COLUMN "parent_recording_id" SET DATA TYPE varchar;
ALTER TABLE "tip_contributions" ALTER COLUMN "token_type" SET NOT NULL;
ALTER TABLE "achievements" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "achievements" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "user_achievements" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "user_achievements" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "user_achievements" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "user_trading_stats" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "user_trading_stats" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "user_trading_stats" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "ai_trading_setups" ADD COLUMN "strategy" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "holding_period" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_type" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_zone" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_timing" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "target_zone" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "stop_loss" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "stop_type" text DEFAULT 'fixed';
ALTER TABLE "ai_trading_setups" ADD COLUMN "trailing_stop_distance" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "max_risk" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "position_size" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "max_drawdown" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "success_probability" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "probability_method" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_value" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "kelly_percentage" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "setup_strength" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "pattern_quality" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "trend_alignment" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "volume_confirmation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "confluence_factors" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "supporting_indicators" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "resistance_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "support_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "fibonacci_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "market_conditions" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "sector_strength" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "correlation_analysis" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "news_analysis" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "optimal_execution" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "slippage_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "liquidity_assessment" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "trading_hours" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_return" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_time_to_target" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "volatility_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "drawdown_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "historical_performance" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "backtest_results" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "similar_setups" text[];
ALTER TABLE "ai_trading_setups" ADD COLUMN "seasonality_bias" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "model_version" text DEFAULT 'v1.0';
ALTER TABLE "ai_trading_setups" ADD COLUMN "model_confidence" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "feature_importance" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "alternative_setups" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "is_triggered" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_executed" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "exit_executed" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "actual_return" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "actual_hold_time" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "user_rating" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "user_notes" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "is_bookmarked" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "sharing_level" text DEFAULT 'private';
ALTER TABLE "ai_trading_setups" ADD COLUMN "updated_at" timestamp DEFAULT now();
ALTER TABLE "ai_trading_setups" ADD COLUMN "last_validated" timestamp DEFAULT now();
ALTER TABLE "ai_trading_setups" ADD COLUMN "tags" text[];
ALTER TABLE "stream_predictions" ADD COLUMN "market_created" boolean DEFAULT false;
ALTER TABLE "stream_predictions" ADD COLUMN "market_id" varchar;
ALTER TABLE "stream_tips" ADD COLUMN "highlight_color" text;
ALTER TABLE "bounty_collaborators" ADD CONSTRAINT "bounty_collaborators_bounty_id_bounties_id_fk" FOREIGN KEY ("bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bounty_collaborators" ADD CONSTRAINT "bounty_collaborators_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bounty_collaborators" ADD CONSTRAINT "bounty_collaborators_invited_by_users_id_fk" FOREIGN KEY ("invited_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "collaboration_sessions" ADD CONSTRAINT "collaboration_sessions_bounty_id_bounties_id_fk" FOREIGN KEY ("bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "copy_trading_positions" ADD CONSTRAINT "copy_trading_positions_copier_id_users_id_fk" FOREIGN KEY ("copier_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "copy_trading_positions" ADD CONSTRAINT "copy_trading_positions_trader_id_traders_id_fk" FOREIGN KEY ("trader_id") REFERENCES "public"."traders"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "copy_trading_positions" ADD CONSTRAINT "copy_trading_positions_signal_id_trading_signals_id_fk" FOREIGN KEY ("signal_id") REFERENCES "public"."trading_signals"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "gamification_notifications" ADD CONSTRAINT "gamification_notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "pattern_alerts" ADD CONSTRAINT "pattern_alerts_parent_alert_id_pattern_alerts_id_fk" FOREIGN KEY ("parent_alert_id") REFERENCES "public"."pattern_alerts"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "trader_performance" ADD CONSTRAINT "trader_performance_trader_id_traders_id_fk" FOREIGN KEY ("trader_id") REFERENCES "public"."traders"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "traders" ADD CONSTRAINT "traders_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "trading_signals" ADD CONSTRAINT "trading_signals_trader_id_traders_id_fk" FOREIGN KEY ("trader_id") REFERENCES "public"."traders"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_daily_quests" ADD CONSTRAINT "user_daily_quests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_daily_quests" ADD CONSTRAINT "user_daily_quests_quest_id_daily_quests_id_fk" FOREIGN KEY ("quest_id") REFERENCES "public"."daily_quests"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_event_participation" ADD CONSTRAINT "user_event_participation_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_event_participation" ADD CONSTRAINT "user_event_participation_event_id_gamification_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."gamification_events"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_follows" ADD CONSTRAINT "user_follows_follower_id_users_id_fk" FOREIGN KEY ("follower_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_follows" ADD CONSTRAINT "user_follows_following_id_users_id_fk" FOREIGN KEY ("following_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_levels" ADD CONSTRAINT "user_levels_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_season_passes" ADD CONSTRAINT "user_season_passes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_season_passes" ADD CONSTRAINT "user_season_passes_season_id_season_passes_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."season_passes"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_streaks" ADD CONSTRAINT "user_streaks_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_weekly_missions" ADD CONSTRAINT "user_weekly_missions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_weekly_missions" ADD CONSTRAINT "user_weekly_missions_mission_id_weekly_missions_id_fk" FOREIGN KEY ("mission_id") REFERENCES "public"."weekly_missions"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "xp_transactions" ADD CONSTRAINT "xp_transactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_trading_setups" ADD CONSTRAINT "ai_trading_setups_alert_id_pattern_alerts_id_fk" FOREIGN KEY ("alert_id") REFERENCES "public"."pattern_alerts"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_avatar1_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar1_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_avatar2_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar2_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_messages" ADD CONSTRAINT "stream_messages_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_messages" ADD CONSTRAINT "stream_messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_messages" ADD CONSTRAINT "stream_messages_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_predictor_id_users_id_fk" FOREIGN KEY ("predictor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_tipper_id_users_id_fk" FOREIGN KEY ("tipper_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_recipient_id_users_id_fk" FOREIGN KEY ("recipient_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_positions" ADD CONSTRAINT "ai_positions_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_positions" ADD CONSTRAINT "ai_positions_agent_id_ai_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."ai_agents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_positions" ADD CONSTRAINT "ai_positions_prediction_id_ai_predictions_id_fk" FOREIGN KEY ("prediction_id") REFERENCES "public"."ai_predictions"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "prediction_markets" ADD CONSTRAINT "prediction_markets_creator_id_users_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "prediction_markets" ADD CONSTRAINT "prediction_markets_source_content_id_summaries_id_fk" FOREIGN KEY ("source_content_id") REFERENCES "public"."summaries"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_predictions" ADD CONSTRAINT "ai_predictions_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_predictions" ADD CONSTRAINT "ai_predictions_agent_id_ai_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."ai_agents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_trades" ADD CONSTRAINT "ai_trades_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_trades" ADD CONSTRAINT "ai_trades_agent_id_ai_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."ai_agents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_trades" ADD CONSTRAINT "ai_trades_position_id_ai_positions_id_fk" FOREIGN KEY ("position_id") REFERENCES "public"."ai_positions"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_trading_alerts" ADD CONSTRAINT "ai_trading_alerts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_content_interactions" ADD CONSTRAINT "avatar_content_interactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_content_interactions" ADD CONSTRAINT "avatar_content_interactions_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_conversations" ADD CONSTRAINT "avatar_conversations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_conversations" ADD CONSTRAINT "avatar_conversations_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_follows" ADD CONSTRAINT "avatar_follows_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_follows" ADD CONSTRAINT "avatar_follows_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_insights" ADD CONSTRAINT "avatar_insights_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_positions" ADD CONSTRAINT "avatar_positions_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_positions" ADD CONSTRAINT "avatar_positions_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_trades" ADD CONSTRAINT "avatar_trades_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_trades" ADD CONSTRAINT "avatar_trades_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bot_performance_snapshots" ADD CONSTRAINT "bot_performance_snapshots_agent_id_ai_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."ai_agents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bot_performance_snapshots" ADD CONSTRAINT "bot_performance_snapshots_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bot_sim_trades" ADD CONSTRAINT "bot_sim_trades_agent_id_ai_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."ai_agents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bot_sim_trades" ADD CONSTRAINT "bot_sim_trades_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bot_stakes" ADD CONSTRAINT "bot_stakes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bot_stakes" ADD CONSTRAINT "bot_stakes_agent_id_ai_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."ai_agents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bot_stakes" ADD CONSTRAINT "bot_stakes_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bounty_engagements" ADD CONSTRAINT "bounty_engagements_bounty_id_bounties_id_fk" FOREIGN KEY ("bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bounty_engagements" ADD CONSTRAINT "bounty_engagements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bounty_hunters" ADD CONSTRAINT "bounty_hunters_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bounty_quality_scores" ADD CONSTRAINT "bounty_quality_scores_bounty_id_bounties_id_fk" FOREIGN KEY ("bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bounty_quality_scores" ADD CONSTRAINT "bounty_quality_scores_summary_id_summaries_id_fk" FOREIGN KEY ("summary_id") REFERENCES "public"."summaries"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bounty_templates" ADD CONSTRAINT "bounty_templates_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "category_follows" ADD CONSTRAINT "category_follows_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "co_stream_sessions" ADD CONSTRAINT "co_stream_sessions_primary_stream_id_live_streams_id_fk" FOREIGN KEY ("primary_stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "co_stream_sessions" ADD CONSTRAINT "co_stream_sessions_primary_host_id_users_id_fk" FOREIGN KEY ("primary_host_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_host_id_users_id_fk" FOREIGN KEY ("host_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_host_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("host_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_linked_bounty_id_bounties_id_fk" FOREIGN KEY ("linked_bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_linked_market_id_prediction_markets_id_fk" FOREIGN KEY ("linked_market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_generated_summary_id_summaries_id_fk" FOREIGN KEY ("generated_summary_id") REFERENCES "public"."summaries"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_parent_id_conversations_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_linked_summary_id_summaries_id_fk" FOREIGN KEY ("linked_summary_id") REFERENCES "public"."summaries"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_linked_bounty_id_bounties_id_fk" FOREIGN KEY ("linked_bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversation_comments" ADD CONSTRAINT "conversation_comments_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversation_comments" ADD CONSTRAINT "conversation_comments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversation_comments" ADD CONSTRAINT "conversation_comments_parent_comment_id_conversation_comments_id_fk" FOREIGN KEY ("parent_comment_id") REFERENCES "public"."conversation_comments"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversation_likes" ADD CONSTRAINT "conversation_likes_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversation_likes" ADD CONSTRAINT "conversation_likes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversation_shares" ADD CONSTRAINT "conversation_shares_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "conversation_shares" ADD CONSTRAINT "conversation_shares_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "daily_login_streak" ADD CONSTRAINT "daily_login_streak_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_debates" ADD CONSTRAINT "stream_debates_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_debates" ADD CONSTRAINT "stream_debates_participant1_id_users_id_fk" FOREIGN KEY ("participant1_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_debates" ADD CONSTRAINT "stream_debates_participant1_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("participant1_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_debates" ADD CONSTRAINT "stream_debates_participant2_id_users_id_fk" FOREIGN KEY ("participant2_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_debates" ADD CONSTRAINT "stream_debates_participant2_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("participant2_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_debates" ADD CONSTRAINT "stream_debates_winner_id_users_id_fk" FOREIGN KEY ("winner_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_debates" ADD CONSTRAINT "stream_debates_winner_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("winner_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "debate_votes" ADD CONSTRAINT "debate_votes_debate_id_stream_debates_id_fk" FOREIGN KEY ("debate_id") REFERENCES "public"."stream_debates"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "debate_votes" ADD CONSTRAINT "debate_votes_voter_id_users_id_fk" FOREIGN KEY ("voter_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "governance_proposals" ADD CONSTRAINT "governance_proposals_proposer_id_users_id_fk" FOREIGN KEY ("proposer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "governance_votes" ADD CONSTRAINT "governance_votes_proposal_id_governance_proposals_id_fk" FOREIGN KEY ("proposal_id") REFERENCES "public"."governance_proposals"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "governance_votes" ADD CONSTRAINT "governance_votes_voter_id_users_id_fk" FOREIGN KEY ("voter_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "prediction_leagues" ADD CONSTRAINT "prediction_leagues_creator_id_users_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "league_participants" ADD CONSTRAINT "league_participants_league_id_prediction_leagues_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."prediction_leagues"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "league_participants" ADD CONSTRAINT "league_participants_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "league_trades" ADD CONSTRAINT "league_trades_league_id_prediction_leagues_id_fk" FOREIGN KEY ("league_id") REFERENCES "public"."prediction_leagues"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "league_trades" ADD CONSTRAINT "league_trades_participant_id_league_participants_id_fk" FOREIGN KEY ("participant_id") REFERENCES "public"."league_participants"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "league_trades" ADD CONSTRAINT "league_trades_market_trade_id_market_trades_id_fk" FOREIGN KEY ("market_trade_id") REFERENCES "public"."market_trades"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_trades" ADD CONSTRAINT "market_trades_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_trades" ADD CONSTRAINT "market_trades_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "learning_lessons" ADD CONSTRAINT "learning_lessons_module_id_learning_modules_id_fk" FOREIGN KEY ("module_id") REFERENCES "public"."learning_modules"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "learning_quizzes" ADD CONSTRAINT "learning_quizzes_lesson_id_learning_lessons_id_fk" FOREIGN KEY ("lesson_id") REFERENCES "public"."learning_lessons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "liquidity_providers" ADD CONSTRAINT "liquidity_providers_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "liquidity_providers" ADD CONSTRAINT "liquidity_providers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_positions" ADD CONSTRAINT "market_positions_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_positions" ADD CONSTRAINT "market_positions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_predictors" ADD CONSTRAINT "market_predictors_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_price_history" ADD CONSTRAINT "market_price_history_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_resolutions" ADD CONSTRAINT "market_resolutions_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_resolutions" ADD CONSTRAINT "market_resolutions_resolved_by_users_id_fk" FOREIGN KEY ("resolved_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "multi_stream_sessions" ADD CONSTRAINT "multi_stream_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "multi_stream_sessions" ADD CONSTRAINT "multi_stream_sessions_primary_stream_id_live_streams_id_fk" FOREIGN KEY ("primary_stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "paper_trades" ADD CONSTRAINT "paper_trades_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "paper_trades" ADD CONSTRAINT "paper_trades_signal_id_trading_signal_history_id_fk" FOREIGN KEY ("signal_id") REFERENCES "public"."trading_signal_history"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "points_transactions" ADD CONSTRAINT "points_transactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolios" ADD CONSTRAINT "portfolios_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_assets" ADD CONSTRAINT "portfolio_assets_portfolio_id_portfolios_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolios"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_assets" ADD CONSTRAINT "portfolio_assets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_goals" ADD CONSTRAINT "portfolio_goals_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_goals" ADD CONSTRAINT "portfolio_goals_portfolio_id_portfolios_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolios"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_insights" ADD CONSTRAINT "portfolio_insights_portfolio_id_portfolios_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolios"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_insights" ADD CONSTRAINT "portfolio_insights_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_snapshots" ADD CONSTRAINT "portfolio_snapshots_portfolio_id_portfolios_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolios"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_snapshots" ADD CONSTRAINT "portfolio_snapshots_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_transactions" ADD CONSTRAINT "portfolio_transactions_portfolio_id_portfolios_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolios"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_transactions" ADD CONSTRAINT "portfolio_transactions_asset_id_portfolio_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."portfolio_assets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "portfolio_transactions" ADD CONSTRAINT "portfolio_transactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "price_alerts" ADD CONSTRAINT "price_alerts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "price_alerts" ADD CONSTRAINT "price_alerts_portfolio_id_portfolios_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolios"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "push_subscriptions" ADD CONSTRAINT "push_subscriptions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "referral_codes" ADD CONSTRAINT "referral_codes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "referral_signups" ADD CONSTRAINT "referral_signups_referral_code_id_referral_codes_id_fk" FOREIGN KEY ("referral_code_id") REFERENCES "public"."referral_codes"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "referral_signups" ADD CONSTRAINT "referral_signups_referrer_id_users_id_fk" FOREIGN KEY ("referrer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "referral_signups" ADD CONSTRAINT "referral_signups_referred_user_id_users_id_fk" FOREIGN KEY ("referred_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_streams" ADD CONSTRAINT "scheduled_streams_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_streams" ADD CONSTRAINT "scheduled_streams_host_id_users_id_fk" FOREIGN KEY ("host_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_streams" ADD CONSTRAINT "scheduled_streams_host_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("host_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_alerts" ADD CONSTRAINT "stream_alerts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_alerts" ADD CONSTRAINT "stream_alerts_streamer_id_users_id_fk" FOREIGN KEY ("streamer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_alerts" ADD CONSTRAINT "stream_alerts_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_chat_command_logs" ADD CONSTRAINT "stream_chat_command_logs_command_id_stream_chat_commands_id_fk" FOREIGN KEY ("command_id") REFERENCES "public"."stream_chat_commands"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_chat_command_logs" ADD CONSTRAINT "stream_chat_command_logs_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_chat_command_logs" ADD CONSTRAINT "stream_chat_command_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_clips" ADD CONSTRAINT "stream_clips_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_clips" ADD CONSTRAINT "stream_clips_creator_id_users_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_participants" ADD CONSTRAINT "stream_participants_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_participants" ADD CONSTRAINT "stream_participants_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_participants" ADD CONSTRAINT "stream_participants_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_conversation_messages" ADD CONSTRAINT "stream_conversation_messages_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_conversation_messages" ADD CONSTRAINT "stream_conversation_messages_participant_id_stream_participants_id_fk" FOREIGN KEY ("participant_id") REFERENCES "public"."stream_participants"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_conversation_messages" ADD CONSTRAINT "stream_conversation_messages_speaker_user_id_users_id_fk" FOREIGN KEY ("speaker_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_conversation_messages" ADD CONSTRAINT "stream_conversation_messages_speaker_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("speaker_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_invitations" ADD CONSTRAINT "stream_invitations_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_invitations" ADD CONSTRAINT "stream_invitations_debate_id_stream_debates_id_fk" FOREIGN KEY ("debate_id") REFERENCES "public"."stream_debates"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_invitations" ADD CONSTRAINT "stream_invitations_inviter_id_users_id_fk" FOREIGN KEY ("inviter_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_invitations" ADD CONSTRAINT "stream_invitations_invitee_id_users_id_fk" FOREIGN KEY ("invitee_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_invitations" ADD CONSTRAINT "stream_invitations_invitee_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("invitee_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_polls" ADD CONSTRAINT "stream_polls_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_polls" ADD CONSTRAINT "stream_polls_creator_id_users_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_poll_votes" ADD CONSTRAINT "stream_poll_votes_poll_id_stream_polls_id_fk" FOREIGN KEY ("poll_id") REFERENCES "public"."stream_polls"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_poll_votes" ADD CONSTRAINT "stream_poll_votes_voter_id_users_id_fk" FOREIGN KEY ("voter_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_questions" ADD CONSTRAINT "stream_questions_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_questions" ADD CONSTRAINT "stream_questions_asker_id_users_id_fk" FOREIGN KEY ("asker_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_raids" ADD CONSTRAINT "stream_raids_from_stream_id_live_streams_id_fk" FOREIGN KEY ("from_stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_raids" ADD CONSTRAINT "stream_raids_to_stream_id_live_streams_id_fk" FOREIGN KEY ("to_stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_raids" ADD CONSTRAINT "stream_raids_raider_id_users_id_fk" FOREIGN KEY ("raider_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_reactions" ADD CONSTRAINT "stream_reactions_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_reactions" ADD CONSTRAINT "stream_reactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_recordings" ADD CONSTRAINT "stream_recordings_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_recordings" ADD CONSTRAINT "stream_recordings_parent_recording_id_stream_recordings_id_fk" FOREIGN KEY ("parent_recording_id") REFERENCES "public"."stream_recordings"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_schedule_reminders" ADD CONSTRAINT "stream_schedule_reminders_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_schedule_reminders" ADD CONSTRAINT "stream_schedule_reminders_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_viewer_leaderboard" ADD CONSTRAINT "stream_viewer_leaderboard_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_viewer_leaderboard" ADD CONSTRAINT "stream_viewer_leaderboard_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "streamer_subscription_tiers" ADD CONSTRAINT "streamer_subscription_tiers_streamer_id_users_id_fk" FOREIGN KEY ("streamer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "streamer_subscriptions" ADD CONSTRAINT "streamer_subscriptions_streamer_id_users_id_fk" FOREIGN KEY ("streamer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "streamer_subscriptions" ADD CONSTRAINT "streamer_subscriptions_subscriber_id_users_id_fk" FOREIGN KEY ("subscriber_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "streamer_subscriptions" ADD CONSTRAINT "streamer_subscriptions_gifted_by_users_id_fk" FOREIGN KEY ("gifted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "super_chats" ADD CONSTRAINT "super_chats_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "super_chats" ADD CONSTRAINT "super_chats_sender_id_users_id_fk" FOREIGN KEY ("sender_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "tip_contributions" ADD CONSTRAINT "tip_contributions_bounty_id_bounties_id_fk" FOREIGN KEY ("bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "tip_contributions" ADD CONSTRAINT "tip_contributions_tipper_id_users_id_fk" FOREIGN KEY ("tipper_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "trading_watchlist" ADD CONSTRAINT "trading_watchlist_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_achievement_id_achievements_id_fk" FOREIGN KEY ("achievement_id") REFERENCES "public"."achievements"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_learning_progress" ADD CONSTRAINT "user_learning_progress_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_learning_progress" ADD CONSTRAINT "user_learning_progress_module_id_learning_modules_id_fk" FOREIGN KEY ("module_id") REFERENCES "public"."learning_modules"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_learning_progress" ADD CONSTRAINT "user_learning_progress_current_lesson_id_learning_lessons_id_fk" FOREIGN KEY ("current_lesson_id") REFERENCES "public"."learning_lessons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_lesson_completions" ADD CONSTRAINT "user_lesson_completions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_lesson_completions" ADD CONSTRAINT "user_lesson_completions_lesson_id_learning_lessons_id_fk" FOREIGN KEY ("lesson_id") REFERENCES "public"."learning_lessons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_lesson_completions" ADD CONSTRAINT "user_lesson_completions_module_id_learning_modules_id_fk" FOREIGN KEY ("module_id") REFERENCES "public"."learning_modules"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_preferences" ADD CONSTRAINT "user_preferences_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_quiz_attempts" ADD CONSTRAINT "user_quiz_attempts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_quiz_attempts" ADD CONSTRAINT "user_quiz_attempts_quiz_id_learning_quizzes_id_fk" FOREIGN KEY ("quiz_id") REFERENCES "public"."learning_quizzes"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_quiz_attempts" ADD CONSTRAINT "user_quiz_attempts_lesson_id_learning_lessons_id_fk" FOREIGN KEY ("lesson_id") REFERENCES "public"."learning_lessons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_stream_achievements" ADD CONSTRAINT "user_stream_achievements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_stream_achievements" ADD CONSTRAINT "user_stream_achievements_achievement_id_stream_achievements_id_fk" FOREIGN KEY ("achievement_id") REFERENCES "public"."stream_achievements"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_stream_settings" ADD CONSTRAINT "user_stream_settings_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_trading_profile" ADD CONSTRAINT "user_trading_profile_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "user_trading_stats" ADD CONSTRAINT "user_trading_stats_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "viewer_watch_rewards" ADD CONSTRAINT "viewer_watch_rewards_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "viewer_watch_rewards" ADD CONSTRAINT "viewer_watch_rewards_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "watchlist_items" ADD CONSTRAINT "watchlist_items_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_posts" ADD CONSTRAINT "avatar_posts_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_posts" ADD CONSTRAINT "avatar_posts_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_posts" ADD CONSTRAINT "avatar_posts_trade_id_avatar_trades_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."avatar_trades"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_posts" ADD CONSTRAINT "avatar_posts_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "avatar_post_reactions" ADD CONSTRAINT "avatar_post_reactions_post_id_avatar_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."avatar_posts"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "avatar_post_reactions" ADD CONSTRAINT "avatar_post_reactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "agent_memory" ADD CONSTRAINT "agent_memory_agent_id_ai_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."ai_agents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "agent_memory" ADD CONSTRAINT "agent_memory_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "market_resolutions_audit" ADD CONSTRAINT "market_resolutions_audit_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "agent_suspensions" ADD CONSTRAINT "agent_suspensions_agent_id_ai_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."ai_agents"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "bridge_requests" ADD CONSTRAINT "bridge_requests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_trading_setups" DROP COLUMN "stop_loss_price";
ALTER TABLE "ai_trading_setups" DROP COLUMN "position_size_percent";
ALTER TABLE "ai_trading_setups" DROP COLUMN "max_risk_percent";
ALTER TABLE "ai_trading_setups" DROP COLUMN "exit_conditions";
ALTER TABLE "ai_trading_setups" DROP COLUMN "invalidation_triggers";
ALTER TABLE "ai_trading_setups" DROP COLUMN "supporting_signals";
ALTER TABLE "ai_trading_setups" DROP COLUMN "confluence_score";
ALTER TABLE "ai_trading_setups" DROP COLUMN "closed_at";
ALTER TABLE "ai_trading_setups" DROP COLUMN "pnl_percent";
ALTER TABLE "ai_trading_setups" DROP COLUMN "generated_by";
ALTER TABLE "scheduled_debates" DROP COLUMN "created_by_user_id";
ALTER TABLE "stream_predictions" DROP COLUMN "created_market_id";
ALTER TABLE "knowledge_avatars" DROP COLUMN "sharpe_ratio";
ALTER TABLE "knowledge_avatars" DROP COLUMN "alpha_generated";
ALTER TABLE "knowledge_avatars" DROP COLUMN "total_investments";
ALTER TABLE "knowledge_avatars" DROP COLUMN "successful_exits";
ALTER TABLE "knowledge_avatars" DROP COLUMN "active_projects";
ALTER TABLE "avatar_insights" DROP COLUMN "updated_at";
ALTER TABLE "bounties" DROP COLUMN "view_count";
ALTER TABLE "bounties" DROP COLUMN "like_count";
ALTER TABLE "bounties" DROP COLUMN "share_count";
ALTER TABLE "stream_recordings" DROP COLUMN "format";
ALTER TABLE "stream_recordings" DROP COLUMN "quality";
ALTER TABLE "stream_recordings" DROP COLUMN "title";
ALTER TABLE "stream_recordings" DROP COLUMN "view_count";
ALTER TABLE "stream_recordings" DROP COLUMN "processed_at";
ALTER TABLE "points_config" ADD CONSTRAINT "points_config_key_unique" UNIQUE("key");
ALTER TABLE "waitlist" ADD CONSTRAINT "waitlist_email_unique" UNIQUE("email");
ALTER TABLE "waitlist" ADD CONSTRAINT "waitlist_unsubscribe_token_unique" UNIQUE("unsubscribe_token");
ALTER TABLE "ai_agents" ADD CONSTRAINT "ai_agents_name_unique" UNIQUE("name");
ALTER TABLE "prediction_markets" ADD CONSTRAINT "prediction_markets_contract_market_id_unique" UNIQUE("contract_market_id");
ALTER TABLE "users" ADD CONSTRAINT "users_twitter_id_unique" UNIQUE("twitter_id");
ALTER TABLE "bounty_hunters" ADD CONSTRAINT "bounty_hunters_user_id_unique" UNIQUE("user_id");
ALTER TABLE "bounty_quality_scores" ADD CONSTRAINT "bounty_quality_scores_bounty_id_unique" UNIQUE("bounty_id");
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_room_id_unique" UNIQUE("room_id");
ALTER TABLE "daily_login_streak" ADD CONSTRAINT "daily_login_streak_user_id_unique" UNIQUE("user_id");
ALTER TABLE "market_predictors" ADD CONSTRAINT "market_predictors_user_id_unique" UNIQUE("user_id");
ALTER TABLE "push_subscriptions" ADD CONSTRAINT "push_subscriptions_endpoint_unique" UNIQUE("endpoint");
ALTER TABLE "referral_codes" ADD CONSTRAINT "referral_codes_code_unique" UNIQUE("code");
ALTER TABLE "stream_chat_commands" ADD CONSTRAINT "stream_chat_commands_command_unique" UNIQUE("command");
ALTER TABLE "achievements" ADD CONSTRAINT "achievements_key_unique" UNIQUE("key");
ALTER TABLE "user_preferences" ADD CONSTRAINT "user_preferences_user_id_unique" UNIQUE("user_id");
ALTER TABLE "user_stream_settings" ADD CONSTRAINT "user_stream_settings_user_id_unique" UNIQUE("user_id");
ALTER TABLE "user_trading_profile" ADD CONSTRAINT "user_trading_profile_user_id_unique" UNIQUE("user_id");
ALTER TABLE "user_trading_stats" ADD CONSTRAINT "user_trading_stats_user_id_unique" UNIQUE("user_id");
ALTER TABLE "tradeable_tokens" ADD CONSTRAINT "tradeable_tokens_symbol_unique" UNIQUE("symbol");
ALTER TABLE "tradeable_tokens" ADD CONSTRAINT "tradeable_tokens_address_unique" UNIQUE("address");
ALTER TABLE "user_trades" ADD CONSTRAINT "user_trades_tx_hash_unique" UNIQUE("tx_hash");
 Warning  Found data-loss statements:
THIS ACTION WILL CAUSE DATA LOSS AND CANNOT BE REVERTED
Do you still want to push changes?
❯ No, abort
  Yes, I want to remove 15 columns, truncate 7 tables [x] All changes were aborted
DROP TABLE "achievement_definitions" CASCADE;
DROP INDEX "idx_asset_price_history_recorded_at";
DROP INDEX "idx_asset_price_history_symbol";
DROP INDEX "idx_ai_agents_is_active";
DROP INDEX "idx_prediction_markets_created_at";
DROP INDEX "idx_prediction_markets_status";
DROP INDEX "idx_ai_trades_agent_id";
DROP INDEX "idx_ai_trades_created_at";
DROP INDEX "idx_ai_trades_market_id";
DROP INDEX "idx_users_twitter_id";
DROP INDEX "idx_users_username";
DROP INDEX "idx_users_wallet_address";
DROP INDEX "idx_avatar_positions_avatar";
DROP INDEX "idx_avatar_positions_market";
DROP INDEX "idx_avatar_trades_avatar";
DROP INDEX "idx_avatar_trades_market";
DROP INDEX "idx_bot_performance_snapshots_agent_id";
DROP INDEX "idx_bot_sim_trades_agent_id";
DROP INDEX "idx_bot_sim_trades_status";
DROP INDEX "idx_bot_stakes_agent_id";
DROP INDEX "idx_bot_stakes_status";
DROP INDEX "idx_bot_stakes_user_id";
DROP INDEX "idx_bounties_created_at";
DROP INDEX "idx_bounties_creator_id";
DROP INDEX "idx_bounties_status";
DROP INDEX "idx_summaries_created_at";
DROP INDEX "idx_summaries_creator_id";
DROP INDEX "idx_market_trades_created_at";
DROP INDEX "idx_market_trades_market_id";
DROP INDEX "idx_portfolio_goals_user_id";
DROP INDEX "idx_price_alerts_active";
DROP INDEX "idx_price_alerts_symbol";
DROP INDEX "idx_price_alerts_user_id";
DROP INDEX "idx_user_interactions_created_at";
DROP INDEX "idx_user_interactions_target_type";
DROP INDEX "idx_user_interactions_user_id";
DROP INDEX "idx_watchlist_items_user_id";
DROP INDEX "idx_avatar_posts_avatar";
DROP INDEX "idx_avatar_posts_created_at";
DROP INDEX "idx_avatar_posts_parent";
DROP INDEX "idx_agent_memory_agent";
DROP INDEX "idx_agent_memory_market_open";
DROP INDEX "idx_agent_suspensions_agent";
DROP INDEX "idx_risk_events_created_at";