ALTER TABLE "achievement_definitions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "achievements" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "achievements" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ai_trading_setups" ADD COLUMN "actual_hold_time" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "actual_return" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "alternative_setups" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "backtest_results" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "confluence_factors" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "correlation_analysis" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "drawdown_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_executed" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_timing" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_type" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "entry_zone" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "exit_executed" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_return" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_time_to_target" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "expected_value" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "feature_importance" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "fibonacci_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "historical_performance" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "holding_period" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "is_bookmarked" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "is_triggered" boolean DEFAULT false;
ALTER TABLE "ai_trading_setups" ADD COLUMN "kelly_percentage" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "last_validated" timestamp DEFAULT now();
ALTER TABLE "ai_trading_setups" ADD COLUMN "liquidity_assessment" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "market_conditions" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "max_drawdown" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "max_risk" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "model_confidence" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "model_version" text DEFAULT 'v1.0';
ALTER TABLE "ai_trading_setups" ADD COLUMN "news_analysis" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "optimal_execution" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "pattern_quality" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "position_size" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "probability_method" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "resistance_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "seasonality_bias" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "sector_strength" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "setup_strength" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "sharing_level" text DEFAULT 'private';
ALTER TABLE "ai_trading_setups" ADD COLUMN "similar_setups" text[];
ALTER TABLE "ai_trading_setups" ADD COLUMN "slippage_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "stop_loss" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "stop_type" text DEFAULT 'fixed';
ALTER TABLE "ai_trading_setups" ADD COLUMN "strategy" text NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "success_probability" real NOT NULL;
ALTER TABLE "ai_trading_setups" ADD COLUMN "supporting_indicators" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "support_levels" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "tags" text[];
ALTER TABLE "ai_trading_setups" ADD COLUMN "target_zone" jsonb;
ALTER TABLE "ai_trading_setups" ADD COLUMN "trading_hours" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "trailing_stop_distance" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "trend_alignment" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "updated_at" timestamp DEFAULT now();
ALTER TABLE "ai_trading_setups" ADD COLUMN "user_notes" text;
ALTER TABLE "ai_trading_setups" ADD COLUMN "user_rating" integer;
ALTER TABLE "ai_trading_setups" ADD COLUMN "volatility_expectation" real;
ALTER TABLE "ai_trading_setups" ADD COLUMN "volume_confirmation" real;
ALTER TABLE "ai_trading_setups" ADD CONSTRAINT "ai_trading_setups_alert_id_pattern_alerts_id_fk" FOREIGN KEY ("alert_id") REFERENCES "public"."pattern_alerts"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ai_trading_setups" ALTER COLUMN "entry_conditions" SET DATA TYPE text[];
ALTER TABLE "ai_trading_setups" ALTER COLUMN "status" SET DEFAULT 'active';
ALTER TABLE "ai_trading_setups" DROP COLUMN "closed_at";
ALTER TABLE "ai_trading_setups" DROP COLUMN "confluence_score";
ALTER TABLE "ai_trading_setups" DROP COLUMN "exit_conditions";
ALTER TABLE "ai_trading_setups" DROP COLUMN "generated_by";
ALTER TABLE "ai_trading_setups" DROP COLUMN "invalidation_triggers";
ALTER TABLE "ai_trading_setups" DROP COLUMN "max_risk_percent";
ALTER TABLE "ai_trading_setups" DROP COLUMN "pnl_percent";
ALTER TABLE "ai_trading_setups" DROP COLUMN "position_size_percent";
ALTER TABLE "ai_trading_setups" DROP COLUMN "stop_loss_price";
ALTER TABLE "ai_trading_setups" DROP COLUMN "supporting_signals";
ALTER TABLE "avatar_content_interactions" ALTER COLUMN "content_id" SET NOT NULL;
ALTER TABLE "avatar_content_interactions" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "avatar_content_interactions" ALTER COLUMN "interaction_type" SET DATA TYPE text;
ALTER TABLE "avatar_follows" ALTER COLUMN "followed_at" DROP NOT NULL;
ALTER TABLE "avatar_follows" ALTER COLUMN "notifications_enabled" DROP NOT NULL;
ALTER TABLE "avatar_insights" ALTER COLUMN "category" DROP NOT NULL;
ALTER TABLE "avatar_insights" ALTER COLUMN "category" SET DATA TYPE text;
ALTER TABLE "avatar_insights" ALTER COLUMN "confidence" SET DATA TYPE integer;
ALTER TABLE "avatar_insights" ALTER COLUMN "confidence" SET DEFAULT 50;
ALTER TABLE "avatar_insights" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "avatar_insights" ALTER COLUMN "insight_type" DROP DEFAULT;
ALTER TABLE "avatar_insights" ALTER COLUMN "published_at" DROP NOT NULL;
ALTER TABLE "avatar_insights" ALTER COLUMN "title" SET DATA TYPE text;
ALTER TABLE "avatar_insights" DROP COLUMN "updated_at";
ALTER TABLE "bounties" ALTER COLUMN "bounty_type" SET NOT NULL;
ALTER TABLE "bounties" ALTER COLUMN "creator_wallet" SET NOT NULL;
ALTER TABLE "bounties" DROP COLUMN "like_count";
ALTER TABLE "bounties" DROP COLUMN "share_count";
ALTER TABLE "bounties" DROP COLUMN "view_count";
ALTER TABLE "knowledge_avatars" ALTER COLUMN "created_at" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "decision_bias" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "expertise" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "follower_count" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "following_count" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "handle" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "is_active" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "max_position_pct" SET DATA TYPE real;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "name" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "risk_tolerance" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "trading_frequency" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "trading_style" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "twitter_handle" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "updated_at" DROP NOT NULL;
ALTER TABLE "knowledge_avatars" ALTER COLUMN "verification_status" SET DATA TYPE text;
ALTER TABLE "knowledge_avatars" DROP COLUMN "active_projects";
ALTER TABLE "knowledge_avatars" DROP COLUMN "alpha_generated";
ALTER TABLE "knowledge_avatars" DROP COLUMN "sharpe_ratio";
ALTER TABLE "knowledge_avatars" DROP COLUMN "successful_exits";
ALTER TABLE "knowledge_avatars" DROP COLUMN "total_investments";
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_generated_summary_id_summaries_id_fk" FOREIGN KEY ("generated_summary_id") REFERENCES "public"."summaries"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_host_avatar_id_knowledge_avatars_id_fk" FOREIGN KEY ("host_avatar_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_host_id_users_id_fk" FOREIGN KEY ("host_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_linked_bounty_id_bounties_id_fk" FOREIGN KEY ("linked_bounty_id") REFERENCES "public"."bounties"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ADD CONSTRAINT "live_streams_linked_market_id_prediction_markets_id_fk" FOREIGN KEY ("linked_market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "live_streams" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "live_streams" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "market_price_history" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "market_price_history" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "portfolio_assets" ALTER COLUMN "annual_growth_rate" SET DATA TYPE real;
ALTER TABLE "portfolio_assets" ALTER COLUMN "contribution_amount" SET DATA TYPE real;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_avatar1_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar1_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_avatar2_id_knowledge_avatars_id_fk" FOREIGN KEY ("avatar2_id") REFERENCES "public"."knowledge_avatars"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ADD CONSTRAINT "scheduled_debates_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "scheduled_debates" ALTER COLUMN "actual_start_time" SET DATA TYPE timestamp;
ALTER TABLE "scheduled_debates" ALTER COLUMN "category" SET DATA TYPE text;
ALTER TABLE "scheduled_debates" ALTER COLUMN "created_at" SET DATA TYPE timestamp;
ALTER TABLE "scheduled_debates" ALTER COLUMN "end_time" SET DATA TYPE timestamp;
ALTER TABLE "scheduled_debates" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "scheduled_debates" ALTER COLUMN "scheduled_start_time" SET DATA TYPE timestamp;
ALTER TABLE "scheduled_debates" ALTER COLUMN "status" SET DATA TYPE text;
ALTER TABLE "scheduled_debates" ALTER COLUMN "status" SET NOT NULL;
ALTER TABLE "scheduled_debates" DROP COLUMN "created_by_user_id";
ALTER TABLE "stream_messages" ADD CONSTRAINT "stream_messages_deleted_by_users_id_fk" FOREIGN KEY ("deleted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_messages" ADD CONSTRAINT "stream_messages_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_messages" ADD CONSTRAINT "stream_messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_messages" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "stream_messages" ALTER COLUMN "deleted_by" SET DATA TYPE varchar;
ALTER TABLE "stream_messages" ALTER COLUMN "message_type" SET NOT NULL;
ALTER TABLE "stream_participants" ADD CONSTRAINT "stream_participants_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_participants" ADD CONSTRAINT "stream_participants_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_participants" ALTER COLUMN "joined_at" SET DEFAULT now();
ALTER TABLE "stream_participants" ALTER COLUMN "participant_type" SET NOT NULL;
ALTER TABLE "stream_participants" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "stream_predictions" ADD COLUMN "market_created" boolean DEFAULT false;
ALTER TABLE "stream_predictions" ADD COLUMN "market_id" varchar;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_market_id_prediction_markets_id_fk" FOREIGN KEY ("market_id") REFERENCES "public"."prediction_markets"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_predictor_id_users_id_fk" FOREIGN KEY ("predictor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ADD CONSTRAINT "stream_predictions_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_predictions" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "stream_predictions" ALTER COLUMN "timestamp" SET DATA TYPE integer;
ALTER TABLE "stream_predictions" DROP COLUMN "created_market_id";
ALTER TABLE "stream_recordings" ALTER COLUMN "duration_seconds" DROP DEFAULT;
ALTER TABLE "stream_recordings" ALTER COLUMN "duration_seconds" DROP NOT NULL;
ALTER TABLE "stream_recordings" ALTER COLUMN "file_size_bytes" SET DATA TYPE integer;
ALTER TABLE "stream_recordings" ALTER COLUMN "id" SET DATA TYPE varchar;
ALTER TABLE "stream_recordings" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "stream_recordings" ALTER COLUMN "parent_recording_id" SET DATA TYPE varchar;
ALTER TABLE "stream_recordings" ALTER COLUMN "recording_url" DROP NOT NULL;
ALTER TABLE "stream_recordings" ALTER COLUMN "status" SET DATA TYPE text;
ALTER TABLE "stream_recordings" ALTER COLUMN "status" SET NOT NULL;
ALTER TABLE "stream_recordings" ALTER COLUMN "stream_id" SET DATA TYPE varchar;
ALTER TABLE "stream_recordings" DROP COLUMN "format";
ALTER TABLE "stream_recordings" DROP COLUMN "processed_at";
ALTER TABLE "stream_recordings" DROP COLUMN "quality";
ALTER TABLE "stream_recordings" DROP COLUMN "title";
ALTER TABLE "stream_recordings" DROP COLUMN "view_count";
ALTER TABLE "stream_tips" ADD COLUMN "highlight_color" text;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_recipient_id_users_id_fk" FOREIGN KEY ("recipient_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_stream_id_live_streams_id_fk" FOREIGN KEY ("stream_id") REFERENCES "public"."live_streams"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ADD CONSTRAINT "stream_tips_tipper_id_users_id_fk" FOREIGN KEY ("tipper_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stream_tips" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "tip_contributions" ALTER COLUMN "token_type" SET NOT NULL;
ALTER TABLE "user_achievements" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "user_achievements" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "user_achievements" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "users" ADD CONSTRAINT "users_twitter_id_unique" UNIQUE("twitter_id");
ALTER TABLE "users" ALTER COLUMN "auth_provider" SET DATA TYPE text;
ALTER TABLE "users" ALTER COLUMN "twitter_display_name" SET DATA TYPE text;
ALTER TABLE "users" ALTER COLUMN "twitter_id" SET DATA TYPE text;
ALTER TABLE "users" ALTER COLUMN "twitter_username" SET DATA TYPE text;
ALTER TABLE "user_trading_stats" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "user_trading_stats" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "user_trading_stats" ALTER COLUMN "updated_at" SET DEFAULT now();
DROP INDEX "idx_agent_memory_agent";
DROP INDEX "idx_agent_memory_market_open";
DROP INDEX "idx_agent_suspensions_agent";
DROP INDEX "idx_ai_agents_is_active";
DROP INDEX "idx_ai_trades_agent_id";
DROP INDEX "idx_ai_trades_created_at";
DROP INDEX "idx_ai_trades_market_id";
DROP INDEX "idx_asset_price_history_recorded_at";
DROP INDEX "idx_asset_price_history_symbol";
DROP INDEX "idx_avatar_positions_avatar";
DROP INDEX "idx_avatar_positions_market";
DROP INDEX "idx_avatar_posts_avatar";
DROP INDEX "idx_avatar_posts_created_at";
DROP INDEX "idx_avatar_posts_parent";
DROP INDEX "idx_avatar_trades_avatar";
DROP INDEX "idx_avatar_trades_market";
DROP INDEX "idx_bot_performance_snapshots_agent_id";
DROP INDEX "idx_bot_sim_trades_agent_id";
DROP INDEX "idx_bot_sim_trades_status";
DROP INDEX "idx_bot_stakes_agent_id";
DROP INDEX "idx_bot_stakes_status";
DROP INDEX "idx_bot_stakes_user_id";
DROP INDEX "idx_bounties_created_at";
DROP INDEX "idx_bounties_creator_id";
DROP INDEX "idx_bounties_status";
DROP INDEX "idx_market_trades_created_at";
DROP INDEX "idx_market_trades_market_id";
DROP INDEX "idx_portfolio_goals_user_id";
DROP INDEX "idx_prediction_markets_created_at";
DROP INDEX "idx_prediction_markets_status";
DROP INDEX "idx_price_alerts_active";
DROP INDEX "idx_price_alerts_symbol";
DROP INDEX "idx_price_alerts_user_id";
DROP INDEX "idx_risk_events_created_at";
DROP INDEX "idx_summaries_created_at";
DROP INDEX "idx_summaries_creator_id";
DROP INDEX "idx_user_interactions_created_at";
DROP INDEX "idx_user_interactions_target_type";
DROP INDEX "idx_user_interactions_user_id";
DROP INDEX "idx_users_twitter_id";
DROP INDEX "idx_users_username";
DROP INDEX "idx_users_wallet_address";
DROP INDEX "idx_watchlist_items_user_id";
DROP TABLE "achievement_definitions" CASCADE;
truncate table "avatar_insights" cascade;
truncate table "knowledge_avatars" cascade;
truncate table "portfolio_assets" cascade;
truncate table "scheduled_debates" cascade;
truncate table "stream_messages" cascade;
truncate table "stream_recordings" cascade;
truncate table "users" cascade;
